BEGIN TRANSACTION;
-- --------------------------------------------------------------------------------------
-- SCRIPT 02: CREACI�N DE PACIENTES Y DIRECCIONES (Morbilidad)
-- --------------------------------------------------------------------------------------
DELETE FROM persona_paciente;
DELETE FROM direccion WHERE id_direccion > 1;

-- 1. INSERTAR PACIENTES (persona_paciente)
INSERT INTO persona_paciente (edad) VALUES (30);
INSERT INTO persona_paciente (edad) VALUES (84);
INSERT INTO persona_paciente (edad) VALUES (47);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (15);
INSERT INTO persona_paciente (edad) VALUES (32);
INSERT INTO persona_paciente (edad) VALUES (44);
INSERT INTO persona_paciente (edad) VALUES (65);
INSERT INTO persona_paciente (edad) VALUES (32);
INSERT INTO persona_paciente (edad) VALUES (90);
INSERT INTO persona_paciente (edad) VALUES (65);
INSERT INTO persona_paciente (edad) VALUES (33);
INSERT INTO persona_paciente (edad) VALUES (83);
INSERT INTO persona_paciente (edad) VALUES (38);
INSERT INTO persona_paciente (edad) VALUES (60);
INSERT INTO persona_paciente (edad) VALUES (31);
INSERT INTO persona_paciente (edad) VALUES (36);
INSERT INTO persona_paciente (edad) VALUES (30);
INSERT INTO persona_paciente (edad) VALUES (3);
INSERT INTO persona_paciente (edad) VALUES (52);
INSERT INTO persona_paciente (edad) VALUES (6);
INSERT INTO persona_paciente (edad) VALUES (18);
INSERT INTO persona_paciente (edad) VALUES (58);
INSERT INTO persona_paciente (edad) VALUES (48);
INSERT INTO persona_paciente (edad) VALUES (84);
INSERT INTO persona_paciente (edad) VALUES (82);
INSERT INTO persona_paciente (edad) VALUES (89);
INSERT INTO persona_paciente (edad) VALUES (13);
INSERT INTO persona_paciente (edad) VALUES (29);
INSERT INTO persona_paciente (edad) VALUES (82);
INSERT INTO persona_paciente (edad) VALUES (45);
INSERT INTO persona_paciente (edad) VALUES (55);
INSERT INTO persona_paciente (edad) VALUES (22);
INSERT INTO persona_paciente (edad) VALUES (48);
INSERT INTO persona_paciente (edad) VALUES (5);
INSERT INTO persona_paciente (edad) VALUES (42);
INSERT INTO persona_paciente (edad) VALUES (76);
INSERT INTO persona_paciente (edad) VALUES (8);
INSERT INTO persona_paciente (edad) VALUES (46);
INSERT INTO persona_paciente (edad) VALUES (28);
INSERT INTO persona_paciente (edad) VALUES (31);
INSERT INTO persona_paciente (edad) VALUES (15);
INSERT INTO persona_paciente (edad) VALUES (23);
INSERT INTO persona_paciente (edad) VALUES (35);
INSERT INTO persona_paciente (edad) VALUES (85);
INSERT INTO persona_paciente (edad) VALUES (51);
INSERT INTO persona_paciente (edad) VALUES (7);
INSERT INTO persona_paciente (edad) VALUES (22);
INSERT INTO persona_paciente (edad) VALUES (18);
INSERT INTO persona_paciente (edad) VALUES (41);
INSERT INTO persona_paciente (edad) VALUES (54);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (7);
INSERT INTO persona_paciente (edad) VALUES (21);
INSERT INTO persona_paciente (edad) VALUES (84);
INSERT INTO persona_paciente (edad) VALUES (70);
INSERT INTO persona_paciente (edad) VALUES (33);
INSERT INTO persona_paciente (edad) VALUES (27);
INSERT INTO persona_paciente (edad) VALUES (46);
INSERT INTO persona_paciente (edad) VALUES (25);
INSERT INTO persona_paciente (edad) VALUES (68);
INSERT INTO persona_paciente (edad) VALUES (8);
INSERT INTO persona_paciente (edad) VALUES (80);
INSERT INTO persona_paciente (edad) VALUES (37);
INSERT INTO persona_paciente (edad) VALUES (25);
INSERT INTO persona_paciente (edad) VALUES (29);
INSERT INTO persona_paciente (edad) VALUES (33);
INSERT INTO persona_paciente (edad) VALUES (6);
INSERT INTO persona_paciente (edad) VALUES (84);
INSERT INTO persona_paciente (edad) VALUES (8);
INSERT INTO persona_paciente (edad) VALUES (79);
INSERT INTO persona_paciente (edad) VALUES (40);
INSERT INTO persona_paciente (edad) VALUES (83);
INSERT INTO persona_paciente (edad) VALUES (39);
INSERT INTO persona_paciente (edad) VALUES (77);
INSERT INTO persona_paciente (edad) VALUES (88);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (43);
INSERT INTO persona_paciente (edad) VALUES (43);
INSERT INTO persona_paciente (edad) VALUES (55);
INSERT INTO persona_paciente (edad) VALUES (42);
INSERT INTO persona_paciente (edad) VALUES (44);
INSERT INTO persona_paciente (edad) VALUES (9);
INSERT INTO persona_paciente (edad) VALUES (1);
INSERT INTO persona_paciente (edad) VALUES (82);
INSERT INTO persona_paciente (edad) VALUES (75);
INSERT INTO persona_paciente (edad) VALUES (23);
INSERT INTO persona_paciente (edad) VALUES (61);
INSERT INTO persona_paciente (edad) VALUES (22);
INSERT INTO persona_paciente (edad) VALUES (4);
INSERT INTO persona_paciente (edad) VALUES (33);
INSERT INTO persona_paciente (edad) VALUES (70);
INSERT INTO persona_paciente (edad) VALUES (89);
INSERT INTO persona_paciente (edad) VALUES (54);
INSERT INTO persona_paciente (edad) VALUES (62);
INSERT INTO persona_paciente (edad) VALUES (56);
INSERT INTO persona_paciente (edad) VALUES (60);
INSERT INTO persona_paciente (edad) VALUES (41);
INSERT INTO persona_paciente (edad) VALUES (49);
INSERT INTO persona_paciente (edad) VALUES (48);
INSERT INTO persona_paciente (edad) VALUES (25);
INSERT INTO persona_paciente (edad) VALUES (47);
INSERT INTO persona_paciente (edad) VALUES (41);
INSERT INTO persona_paciente (edad) VALUES (86);
INSERT INTO persona_paciente (edad) VALUES (24);
INSERT INTO persona_paciente (edad) VALUES (31);
INSERT INTO persona_paciente (edad) VALUES (22);
INSERT INTO persona_paciente (edad) VALUES (65);
INSERT INTO persona_paciente (edad) VALUES (53);
INSERT INTO persona_paciente (edad) VALUES (86);
INSERT INTO persona_paciente (edad) VALUES (78);
INSERT INTO persona_paciente (edad) VALUES (29);
INSERT INTO persona_paciente (edad) VALUES (20);
INSERT INTO persona_paciente (edad) VALUES (6);
INSERT INTO persona_paciente (edad) VALUES (87);
INSERT INTO persona_paciente (edad) VALUES (14);
INSERT INTO persona_paciente (edad) VALUES (49);
INSERT INTO persona_paciente (edad) VALUES (2);
INSERT INTO persona_paciente (edad) VALUES (71);
INSERT INTO persona_paciente (edad) VALUES (34);
INSERT INTO persona_paciente (edad) VALUES (50);
INSERT INTO persona_paciente (edad) VALUES (9);
INSERT INTO persona_paciente (edad) VALUES (50);
INSERT INTO persona_paciente (edad) VALUES (85);
INSERT INTO persona_paciente (edad) VALUES (39);
INSERT INTO persona_paciente (edad) VALUES (11);
INSERT INTO persona_paciente (edad) VALUES (49);
INSERT INTO persona_paciente (edad) VALUES (84);
INSERT INTO persona_paciente (edad) VALUES (25);
INSERT INTO persona_paciente (edad) VALUES (41);
INSERT INTO persona_paciente (edad) VALUES (82);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (20);
INSERT INTO persona_paciente (edad) VALUES (16);
INSERT INTO persona_paciente (edad) VALUES (3);
INSERT INTO persona_paciente (edad) VALUES (29);
INSERT INTO persona_paciente (edad) VALUES (23);
INSERT INTO persona_paciente (edad) VALUES (32);
INSERT INTO persona_paciente (edad) VALUES (9);
INSERT INTO persona_paciente (edad) VALUES (76);
INSERT INTO persona_paciente (edad) VALUES (73);
INSERT INTO persona_paciente (edad) VALUES (18);
INSERT INTO persona_paciente (edad) VALUES (54);
INSERT INTO persona_paciente (edad) VALUES (79);
INSERT INTO persona_paciente (edad) VALUES (51);
INSERT INTO persona_paciente (edad) VALUES (68);
INSERT INTO persona_paciente (edad) VALUES (25);
INSERT INTO persona_paciente (edad) VALUES (49);
INSERT INTO persona_paciente (edad) VALUES (87);
INSERT INTO persona_paciente (edad) VALUES (28);
INSERT INTO persona_paciente (edad) VALUES (49);
INSERT INTO persona_paciente (edad) VALUES (22);
INSERT INTO persona_paciente (edad) VALUES (80);
INSERT INTO persona_paciente (edad) VALUES (83);
INSERT INTO persona_paciente (edad) VALUES (89);
INSERT INTO persona_paciente (edad) VALUES (79);
INSERT INTO persona_paciente (edad) VALUES (35);
INSERT INTO persona_paciente (edad) VALUES (52);
INSERT INTO persona_paciente (edad) VALUES (77);
INSERT INTO persona_paciente (edad) VALUES (79);
INSERT INTO persona_paciente (edad) VALUES (18);
INSERT INTO persona_paciente (edad) VALUES (1);
INSERT INTO persona_paciente (edad) VALUES (5);
INSERT INTO persona_paciente (edad) VALUES (51);
INSERT INTO persona_paciente (edad) VALUES (39);
INSERT INTO persona_paciente (edad) VALUES (70);
INSERT INTO persona_paciente (edad) VALUES (61);
INSERT INTO persona_paciente (edad) VALUES (36);
INSERT INTO persona_paciente (edad) VALUES (27);
INSERT INTO persona_paciente (edad) VALUES (9);
INSERT INTO persona_paciente (edad) VALUES (50);
INSERT INTO persona_paciente (edad) VALUES (12);
INSERT INTO persona_paciente (edad) VALUES (40);
INSERT INTO persona_paciente (edad) VALUES (31);
INSERT INTO persona_paciente (edad) VALUES (78);
INSERT INTO persona_paciente (edad) VALUES (31);
INSERT INTO persona_paciente (edad) VALUES (89);
INSERT INTO persona_paciente (edad) VALUES (74);
INSERT INTO persona_paciente (edad) VALUES (10);
INSERT INTO persona_paciente (edad) VALUES (56);
INSERT INTO persona_paciente (edad) VALUES (41);
INSERT INTO persona_paciente (edad) VALUES (32);
INSERT INTO persona_paciente (edad) VALUES (26);
INSERT INTO persona_paciente (edad) VALUES (68);
INSERT INTO persona_paciente (edad) VALUES (8);
INSERT INTO persona_paciente (edad) VALUES (72);
INSERT INTO persona_paciente (edad) VALUES (86);
INSERT INTO persona_paciente (edad) VALUES (80);
INSERT INTO persona_paciente (edad) VALUES (80);
INSERT INTO persona_paciente (edad) VALUES (46);
INSERT INTO persona_paciente (edad) VALUES (80);
INSERT INTO persona_paciente (edad) VALUES (47);
INSERT INTO persona_paciente (edad) VALUES (67);
INSERT INTO persona_paciente (edad) VALUES (14);
INSERT INTO persona_paciente (edad) VALUES (8);
INSERT INTO persona_paciente (edad) VALUES (16);
INSERT INTO persona_paciente (edad) VALUES (12);
INSERT INTO persona_paciente (edad) VALUES (79);
INSERT INTO persona_paciente (edad) VALUES (63);
INSERT INTO persona_paciente (edad) VALUES (53);
INSERT INTO persona_paciente (edad) VALUES (64);
INSERT INTO persona_paciente (edad) VALUES (19);
INSERT INTO persona_paciente (edad) VALUES (86);
INSERT INTO persona_paciente (edad) VALUES (71);
INSERT INTO persona_paciente (edad) VALUES (13);
INSERT INTO persona_paciente (edad) VALUES (14);
INSERT INTO persona_paciente (edad) VALUES (74);
INSERT INTO persona_paciente (edad) VALUES (20);
INSERT INTO persona_paciente (edad) VALUES (49);
INSERT INTO persona_paciente (edad) VALUES (43);
INSERT INTO persona_paciente (edad) VALUES (25);
INSERT INTO persona_paciente (edad) VALUES (87);
INSERT INTO persona_paciente (edad) VALUES (26);
INSERT INTO persona_paciente (edad) VALUES (57);
INSERT INTO persona_paciente (edad) VALUES (20);
INSERT INTO persona_paciente (edad) VALUES (42);
INSERT INTO persona_paciente (edad) VALUES (13);
INSERT INTO persona_paciente (edad) VALUES (22);
INSERT INTO persona_paciente (edad) VALUES (81);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (59);
INSERT INTO persona_paciente (edad) VALUES (37);
INSERT INTO persona_paciente (edad) VALUES (5);
INSERT INTO persona_paciente (edad) VALUES (45);
INSERT INTO persona_paciente (edad) VALUES (21);
INSERT INTO persona_paciente (edad) VALUES (48);
INSERT INTO persona_paciente (edad) VALUES (62);
INSERT INTO persona_paciente (edad) VALUES (60);
INSERT INTO persona_paciente (edad) VALUES (89);
INSERT INTO persona_paciente (edad) VALUES (28);
INSERT INTO persona_paciente (edad) VALUES (63);
INSERT INTO persona_paciente (edad) VALUES (3);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (79);
INSERT INTO persona_paciente (edad) VALUES (24);
INSERT INTO persona_paciente (edad) VALUES (37);
INSERT INTO persona_paciente (edad) VALUES (14);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (52);
INSERT INTO persona_paciente (edad) VALUES (36);
INSERT INTO persona_paciente (edad) VALUES (19);
INSERT INTO persona_paciente (edad) VALUES (3);
INSERT INTO persona_paciente (edad) VALUES (72);
INSERT INTO persona_paciente (edad) VALUES (57);
INSERT INTO persona_paciente (edad) VALUES (62);
INSERT INTO persona_paciente (edad) VALUES (76);
INSERT INTO persona_paciente (edad) VALUES (60);
INSERT INTO persona_paciente (edad) VALUES (7);
INSERT INTO persona_paciente (edad) VALUES (61);
INSERT INTO persona_paciente (edad) VALUES (28);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (28);
INSERT INTO persona_paciente (edad) VALUES (2);
INSERT INTO persona_paciente (edad) VALUES (40);
INSERT INTO persona_paciente (edad) VALUES (32);
INSERT INTO persona_paciente (edad) VALUES (85);
INSERT INTO persona_paciente (edad) VALUES (87);
INSERT INTO persona_paciente (edad) VALUES (13);
INSERT INTO persona_paciente (edad) VALUES (12);
INSERT INTO persona_paciente (edad) VALUES (77);
INSERT INTO persona_paciente (edad) VALUES (29);
INSERT INTO persona_paciente (edad) VALUES (33);
INSERT INTO persona_paciente (edad) VALUES (14);
INSERT INTO persona_paciente (edad) VALUES (9);
INSERT INTO persona_paciente (edad) VALUES (13);
INSERT INTO persona_paciente (edad) VALUES (57);
INSERT INTO persona_paciente (edad) VALUES (7);
INSERT INTO persona_paciente (edad) VALUES (86);
INSERT INTO persona_paciente (edad) VALUES (22);
INSERT INTO persona_paciente (edad) VALUES (15);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (52);
INSERT INTO persona_paciente (edad) VALUES (23);
INSERT INTO persona_paciente (edad) VALUES (21);
INSERT INTO persona_paciente (edad) VALUES (24);
INSERT INTO persona_paciente (edad) VALUES (39);
INSERT INTO persona_paciente (edad) VALUES (60);
INSERT INTO persona_paciente (edad) VALUES (41);
INSERT INTO persona_paciente (edad) VALUES (4);
INSERT INTO persona_paciente (edad) VALUES (69);
INSERT INTO persona_paciente (edad) VALUES (8);
INSERT INTO persona_paciente (edad) VALUES (43);
INSERT INTO persona_paciente (edad) VALUES (56);
INSERT INTO persona_paciente (edad) VALUES (30);
INSERT INTO persona_paciente (edad) VALUES (81);
INSERT INTO persona_paciente (edad) VALUES (47);
INSERT INTO persona_paciente (edad) VALUES (18);
INSERT INTO persona_paciente (edad) VALUES (24);
INSERT INTO persona_paciente (edad) VALUES (88);
INSERT INTO persona_paciente (edad) VALUES (79);
INSERT INTO persona_paciente (edad) VALUES (70);
INSERT INTO persona_paciente (edad) VALUES (19);
INSERT INTO persona_paciente (edad) VALUES (37);
INSERT INTO persona_paciente (edad) VALUES (13);
INSERT INTO persona_paciente (edad) VALUES (53);
INSERT INTO persona_paciente (edad) VALUES (58);
INSERT INTO persona_paciente (edad) VALUES (59);
INSERT INTO persona_paciente (edad) VALUES (86);
INSERT INTO persona_paciente (edad) VALUES (77);
INSERT INTO persona_paciente (edad) VALUES (5);

-- 2. INSERTAR DIRECCIONES DE HOGAR
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 21, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 30, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 99, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 50, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 26, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 49, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 23, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 83, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 31, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 28, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 26, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 40, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 72, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 22, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 55, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 19, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 57, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 70, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 24, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 42, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 91, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 33, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 93, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 99, Sector Vía San Tomé, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 14, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 86, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 90, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 8, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 73, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 52, Sector El Palomar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 49, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 77, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 98, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 94, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 95, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 36, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 63, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 19, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 82, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 10, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 28, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 33, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 31, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 21, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 33, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 10, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 59, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 97, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 51, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 28, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 17, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 49, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 82, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 71, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 94, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 72, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 10, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 65, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 10, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 97, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 69, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 53, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 2, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 58, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 89, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 59, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 31, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 12, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 11, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 13, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 12, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 99, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 100, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 27, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 12, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 24, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 26, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 39, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 57, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 22, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 49, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 11, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 10, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 66, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 84, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 80, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 96, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 67, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 12, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 11, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 38, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 39, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 86, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 14, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 45, Sector Vía San Tomé, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 96, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 19, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 37, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 25, Sector El Palomar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 5, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 44, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 80, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 55, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 71, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 13, Sector Vía San Tomé, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 9, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 39, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 31, Sector El Palomar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 52, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 76, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 67, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 57, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 71, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 54, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 97, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 26, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 63, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 30, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 55, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 77, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 25, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 11, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 81, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 12, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 92, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 2, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 51, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 11, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 90, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 98, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 59, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 24, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 93, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 68, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 64, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 64, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 51, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 19, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 40, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 71, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 35, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 67, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 52, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 73, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 45, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 68, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 58, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 37, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 1, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 50, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 7, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 95, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 96, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 54, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 61, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 45, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 40, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 40, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 22, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 54, Sector Vía San Tomé, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 20, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 89, Sector Vía San Tomé, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 8, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 92, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 66, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 95, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 52, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 58, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 8, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 81, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 46, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 4, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 24, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 64, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 60, Sector El Palomar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 5, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 32, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 65, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 7, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 17, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 37, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 59, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 8, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 86, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 18, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 17, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 63, Sector Vía San Tomé, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 85, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 2, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 91, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 16, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 79, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 65, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 20, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 100, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 59, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 90, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 7, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 3, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 93, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 56, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 40, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 24, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 90, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 65, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 74, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 13, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 48, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 50, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 30, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 73, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 62, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 3, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 70, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 84, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 99, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 68, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 68, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 21, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 51, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 14, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 17, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 95, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 5, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 13, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 56, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 66, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 55, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 91, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 42, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 100, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 74, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 59, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 75, Sector El Palomar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 39, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 13, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 41, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 36, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 3, Sector El Palomar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 92, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 76, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 25, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 47, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 36, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 51, Sector El Palomar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 1, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 18, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 37, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 38, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 2, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 49, Sector Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 63, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 98, Sector El Palomar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 82, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 8, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 23, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 42, Sector Vía Clarines, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 49, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 86, Sector Pueblo Nuevo Sur, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 8, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 31, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 75, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 84, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 42, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 2, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 70, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 42, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 60, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 82, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 64, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 61, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 42, Sector Vía San Tomé, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 74, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 39, Sector El Palomar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 75, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 56, Sector Los Olivos, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 27, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 95, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 59, Sector Casco Central, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 22, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 4, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 71, Sector Las Malvinas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 93, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 36, Sector El Palomar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 12, Sector Campo Alegre, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 32, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 77, Sector Barrio Simón Bolívar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 41, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 10, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 25, Sector El Palomar, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 99, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 67, Sector El Casco, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 53, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 67, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 13, Sector La Esperanza, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 23, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 54, Sector El Centro, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 62, Sector Punta de Mata, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 88, Sector Sector Las Vegas, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 81, Sector Km 55, cerca del CDI.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
COMMIT;

-- Mapeo de datos guardado en 'morbilidad_data_mapping.json' para el SCRIPT 03.
