BEGIN TRANSACTION;
-- --------------------------------------------------------------------------------------
-- SCRIPT 03: REGISTROS FINALES DE MORBILIDAD
-- Inserta 300 registros en morbilidad usando la secuencia de IDs generada en el SCRIPT 02.
-- --------------------------------------------------------------------------------------
DELETE FROM morbilidad;
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (1, 2, 'José Ramírez Restrepo', 'Difteria', '2025-02-13');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (2, 3, 'Génesis Briceño Jaimes', 'Hernia discal', '2025-02-28');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (3, 4, 'Mayerling Uribe Blanco', 'Neumonía', '2024-10-27');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (4, 5, 'Ronaldo Cicero Pérez', 'Tuberculosis', '2024-09-21');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (5, 6, 'Mariana Fernández Cicero', 'Gastritis', '2025-05-23');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (6, 7, 'Rosa María Paz Arcila', 'Enfermedad de Crohn', '2025-04-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (7, 8, 'Diana Lara García', 'Malaria', '2025-05-12');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (8, 9, 'Mario Redondo Duarte', 'Intolerancia a la lactosa', '2024-09-06');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (9, 10, 'Javier Molina Cabrera', 'Cáncer de próstata', '2024-10-18');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (10, 11, 'Bernarda Gallegos Romero', 'Gripe (influenza)', '2025-05-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (11, 12, 'Yusbely Colmenares Salcedo', 'Abdomen agudo', '2025-06-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (12, 13, 'Benjamín Gutiérrez Murillo', 'Sordera', '2025-01-21');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (13, 14, 'Edith Carrillo Marcano', 'Rubéola', '2024-05-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (14, 15, 'Alejandra Valdez Mora', 'Tuberculosis', '2024-01-22');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (15, 16, 'Luis Bandres Aranda', 'VIH/SIDA', '2024-04-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (16, 17, 'Consuelo Gómez Montes', 'Fiebre tifoidea', '2024-04-15');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (17, 18, 'Elvira Rivera Campo', 'Enfermedad de Crohn', '2025-04-24');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (18, 19, 'Nora Trejo Consalvi', 'Fiebre amarilla', '2025-01-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (19, 20, 'René Trejo Pereira', 'Mononucleosis infecciosa', '2024-05-15');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (20, 21, 'Isabel Salcedo Cardona', 'Osteoporosis', '2024-01-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (21, 22, 'Olivia Aguilar Caraballo', 'Pielonefritis', '2024-03-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (22, 23, 'Fermín Granados Izquierdo', 'Insuficiencia respiratoria baja', '2024-02-10');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (23, 24, 'Salvador Navarro Guerra', 'Pielonefritis', '2024-12-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (24, 25, 'José Salcedo Pereira', 'Rinitis alérgica', '2024-06-18');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (25, 26, 'Mariángel Barros Morales', 'Trastorno bipolar', '2024-02-24');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (26, 27, 'Rigoberto Colmenares Benitez', 'Úlcera gástrica', '2025-11-14');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (27, 28, 'Tomás Roldán Briceño', 'Difteria', '2024-09-06');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (28, 29, 'Patricia Reyes Ospina', 'Apendicitis', '2025-02-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (29, 30, 'Eva Trujillo Zambrano', 'Fiebre amarilla', '2025-01-11');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (30, 31, 'Eva Barboza Gómez', 'Enfermedad de Crohn', '2024-06-13');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (31, 32, 'Iván Bravo Gómez', 'Dengue', '2025-12-12');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (32, 33, 'Gerardo Bolivar Cadenas', 'Rubéola', '2025-09-21');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (33, 34, 'Mateo Colmenares Velásquez', 'Mononucleosis infecciosa', '2024-01-21');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (34, 35, 'Ángel López Aular', 'Esclerosis múltiple', '2025-12-09');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (35, 36, 'Amparo Bustamante Bernal', 'Trastorno de ansiedad generalizada', '2024-06-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (36, 37, 'Gladys Calles Carrillo', 'EPOC (Enfermedad Pulmonar Obstructiva Crónica)', '2024-04-05');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (37, 38, 'Daniel Morales Betancourt', 'Enfermedad de Graves', '2025-07-15');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (38, 39, 'Irene Flores Gómez', 'Ansiedad', '2024-08-27');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (39, 40, 'Manuela Valencia Torres', 'Meningitis', '2024-12-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (40, 41, 'Ángela Ortiz Reyes', 'Psoriasis', '2025-04-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (41, 42, 'Julia Núñez López', 'COVID-19', '2024-11-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (42, 43, 'Julian Jiménez Chávez', 'Alzheimer', '2025-03-12');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (43, 44, 'Fidel Maldonado Álvarez', 'Vértigo', '2024-04-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (44, 45, 'Emanuel Bernal Granados', 'Sarampión', '2024-12-07');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (45, 46, 'Bernarda Carreño Álvarez', 'Esclerosis múltiple', '2025-11-23');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (46, 47, 'Luisana Salcedo Arévalo', 'Hipercolesterolemia', '2025-09-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (47, 48, 'Walter Véliz Gil', 'Enfermedad de Parkinson', '2025-03-11');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (48, 49, 'Luisana Ortega Gallegos', 'Cistitis', '2025-12-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (49, 50, 'Inés Cárdenas Brito', 'Cistitis', '2024-03-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (50, 51, 'Josefina Urdaneta Ortiz', 'Reflujo gastroesofágico (ERGE)', '2025-08-19');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (51, 52, 'Consuelo Rincón Peraza', 'Bronquitis', '2024-03-13');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (52, 53, 'Saúl Toro Carvajal', 'Esófago de Barrett', '2024-03-24');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (53, 54, 'Rodrigo Fajardo Lara', 'Fiebre amarilla', '2025-08-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (54, 55, 'Adriana Roldán Caballero', 'Fiebre tifoidea', '2025-01-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (55, 56, 'Luisa Henríquez Navia', 'Cirrosis hepática', '2024-09-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (56, 57, 'Maximiliano Burgos Arévalo', 'Hipercolesterolemia', '2024-01-19');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (57, 58, 'Yolanda Arteaga Quintero', 'Varicela', '2025-11-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (58, 59, 'Olivia Zambrano Briceño', 'Neumonía', '2025-04-27');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (59, 60, 'Sofía Bandres Barreto', 'EPOC (Enfermedad Pulmonar Obstructiva Crónica)', '2024-08-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (60, 61, 'Martín Cabrera Yánez', 'Asma', '2024-01-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (61, 62, 'Ramón López Borjas', 'Insomnio', '2024-11-10');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (62, 63, 'Isabel Villegas Delgado', 'Fibromialgia', '2025-11-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (63, 64, 'Gregorio Téllez Barreto', 'Esquizofrenia', '2025-11-11');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (64, 65, 'Lismar Arroyo Ramírez', 'Hipercolesterolemia', '2025-10-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (65, 66, 'Yulimar Zambrano Quintero', 'Leucemia', '2024-04-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (66, 67, 'Carmen Arrate Bohorquez', 'Síncope', '2025-08-12');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (67, 68, 'Cristian Borjas Arévalo', 'Esófago de Barrett', '2025-02-23');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (68, 69, 'Carolina Bello Briceño', 'Dengue', '2024-10-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (69, 70, 'José Arroyo Cicero', 'Trombosis', '2025-01-11');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (70, 71, 'Luisana Velásquez Véliz', 'Lues connatal', '2025-01-21');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (71, 72, 'Leonardo Valenzuela Uribe', 'Bronquitis', '2025-09-18');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (72, 73, 'Guillermo Galindo Arcila', 'Gripe (influenza)', '2025-12-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (73, 74, 'Oriana Jaimes Cadenas', 'Osteoartritis', '2024-12-21');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (74, 75, 'Esteban Aular Cicero', 'Osteoporosis', '2024-04-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (75, 76, 'Rocío Paz Zambrano', 'VIH/SIDA', '2025-07-22');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (76, 77, 'Adrián Núñez Mora', 'Resfriado común', '2025-01-10');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (77, 78, 'Julio Cano Fuentes', 'Esquizofrenia', '2024-04-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (78, 79, 'Lourdes Padilla Gutiérrez', 'Gastritis', '2024-08-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (79, 80, 'Dolores Quintero Correa', 'Esclerosis múltiple', '2025-08-18');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (80, 81, 'Luisa Gómez Bohorquez', 'Virus del Papiloma Humano (VPH)', '2025-09-20');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (81, 82, 'Yulimar Redondo Villegas', 'Varicela', '2025-05-10');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (82, 83, 'Simón Guerra Guerra', 'Hipertiroidismo', '2025-02-09');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (83, 84, 'Armando Zambrano Suárez', 'Cistitis', '2024-02-28');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (84, 85, 'Esteban Izquierdo Escobar', 'Vértigo', '2025-05-14');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (85, 86, 'Beatriz Briceño Hernández', 'Depresión', '2025-03-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (86, 87, 'Héctor Bohorquez Barros', 'Epilepsia', '2025-06-05');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (87, 88, 'Victor Ramírez Ruiz', 'Infarto agudo al miocardio', '2024-12-29');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (88, 89, 'Camila Arias Estrada', 'Infarto agudo al miocardio', '2025-07-12');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (89, 90, 'Juana Arguello Granados', 'Enfermedad de Graves', '2024-10-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (90, 91, 'Gloria Quintero Vidal', 'Cáncer de próstata', '2025-08-24');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (91, 92, 'Francisca Prieto Rangel', 'Alzheimer', '2024-11-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (92, 93, 'Enrique Pereira Aguilar', 'Trastorno de ansiedad generalizada', '2024-01-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (93, 94, 'Ruth Yépez Jiménez', 'Neumonía', '2025-03-07');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (94, 95, 'Cecilia Vera Navarro', 'Obstrucción intestinal', '2025-03-28');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (95, 96, 'Camila Carreño Salas', 'Cirrosis hepática', '2025-04-28');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (96, 97, 'Alejandro Alvarado Zambrano', 'Cefalea tensional', '2024-10-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (97, 98, 'Javier Barros Rincón', 'Osteoartritis', '2024-04-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (98, 99, 'Leonardo Cabrera Trujillo', 'Obesidad', '2024-04-27');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (99, 100, 'Erick Celis Avila', 'Diabetes tipo 2', '2024-10-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (100, 101, 'Nora Arteaga Arrate', 'Epilepsia', '2025-09-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (101, 102, 'Ángel Carvajal Salinas', 'Guillain-Barré (síndrome de)', '2024-12-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (102, 103, 'Gonzalo Henríquez Jaimes', 'Enfermedad de Ménière', '2024-03-09');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (103, 104, 'Maximiliano Vera Benitez', 'Hipertensión arterial', '2024-03-29');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (104, 105, 'Lucas Contreras Lucena', 'Asma', '2025-05-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (105, 106, 'Daniela Ortiz Cisneros', 'Enfermedad de Ménière', '2024-01-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (106, 107, 'Pedro Villalobos Quintero', 'Lumbalgia', '2024-04-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (107, 108, 'Santiago Azocar Baron', 'Malaria', '2025-09-23');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (108, 109, 'Olivia Ramírez Mendoza', 'Esclerosis múltiple', '2025-07-05');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (109, 110, 'Santiago Arjona Marcano', 'Lumbalgia', '2025-08-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (110, 111, 'Valentina Calderón Bolivar', 'Infarto agudo al miocardio', '2025-04-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (111, 112, 'Berta Arguello Prieto', 'Infarto agudo al miocardio', '2025-09-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (112, 113, 'Javier Causado Rodríguez', 'Estreñimiento', '2024-03-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (113, 114, 'Ana Núñez Arroyo', 'COVID-19', '2025-12-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (114, 115, 'Elisa Salcedo Soto', 'Infarto agudo al miocardio', '2024-02-21');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (115, 116, 'Oriana Díaz Chávez', 'Vértigo', '2025-05-27');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (116, 117, 'David Castro Castañeda', 'Ansiedad', '2025-05-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (117, 118, 'Julian Quintero Briceño', 'Obstrucción intestinal', '2024-02-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (118, 119, 'Marta Vargas González', 'Dispepsia funcional', '2024-06-05');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (119, 120, 'Yolanda Bello Causado', 'Fiebre amarilla', '2025-08-24');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (120, 121, 'Bernarda Arias Bermúdez', 'Hipotiroidismo', '2025-12-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (121, 122, 'Nora Barreto Pereira', 'Osteoporosis', '2025-11-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (122, 123, 'Rodrigo Soto Sánchez', 'Anemia', '2024-05-19');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (123, 124, 'Gregorio Casas Bello', 'TDAH (Trastorno por Déficit de Atención e Hiperactividad)', '2025-02-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (124, 125, 'Rodrigo Alvarado Serrano', 'Diabetes tipo 1', '2025-04-22');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (125, 126, 'Rigoberto Valenzuela Murillo', 'Trombosis', '2024-02-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (126, 127, 'Ramiro Alvarado Zambrano', 'Mononucleosis infecciosa', '2024-02-10');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (127, 128, 'Isabel Rosales Méndez', 'Epilepsia', '2025-08-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (128, 129, 'Eva Zambrano Jaimes', 'Pielonefritis', '2024-02-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (129, 130, 'Salvador Cortez Vidal', 'Insomnio', '2024-11-14');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (130, 131, 'Victor Báez Mendoza', 'Miomatosis uterina', '2025-02-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (131, 132, 'Gregorio Marques Calles', 'Vértigo', '2025-03-24');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (132, 133, 'Daniel Castillo Cantillo', 'Obesidad', '2025-05-10');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (133, 134, 'Miriam Redondo Moreno', 'Zoster (culebrilla)', '2024-01-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (134, 135, 'Luis Rodríguez Caraballo', 'Abdomen agudo', '2024-07-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (135, 136, 'Jesús Carvajal Cisneros', 'Úlcera gástrica', '2024-11-20');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (136, 137, 'Inés Reyes Villalobos', 'Enfermedad de Crohn', '2025-03-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (137, 138, 'Walter Vega Trejo', 'Osteoartritis', '2025-03-19');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (138, 139, 'Jesús Caballero Rivera', 'Insomnio', '2024-06-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (139, 140, 'Julio Castañeda Lucena', 'Cefalea tensional', '2025-06-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (140, 141, 'Luisa Véliz Molina', 'Retinopatía diabética', '2025-12-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (141, 142, 'Yulimar Salinas Hernández', 'Retinopatía diabética', '2025-04-27');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (142, 143, 'Alba Torres Romero', 'Hepatitis C', '2025-11-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (143, 144, 'Gabriel Hernández Paredes', 'Alzheimer', '2025-03-10');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (144, 145, 'Ronaldo Cedeno Salazar', 'Lumbalgia', '2025-10-11');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (145, 146, 'Carmen Bustamante Castro', 'Lues connatal', '2024-05-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (146, 147, 'Valentina Campos Figueroa', 'Gastritis', '2024-01-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (147, 148, 'Luisana Salas Galindo', 'Malaria', '2025-08-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (148, 149, 'Armando Reyes Mora', 'Úlcera gástrica', '2024-03-09');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (149, 150, 'Xiomara Granados Torres', 'Dengue', '2025-05-24');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (150, 151, 'Ruth Granados Cruz', 'Insomnio', '2024-05-29');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (151, 152, 'Pedro Bohorquez Arias', 'Insomnio', '2024-12-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (152, 153, 'Soledad Celis Vera', 'Estreñimiento', '2025-10-06');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (153, 154, 'Agustín Guerrero Ospina', 'Obstrucción intestinal', '2025-10-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (154, 155, 'Edith Izquierdo Betancourt', 'Leucemia', '2024-04-27');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (155, 156, 'Xiomara Rivera Calderón', 'Anemia', '2025-09-19');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (156, 157, 'Lourdes Marcano Barrios', 'Malaria', '2025-04-06');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (157, 158, 'Rafael Olivo Arrate', 'Hepatitis A', '2025-10-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (158, 159, 'Julia Bohorquez Gutiérrez', 'Cefalea tensional', '2025-01-10');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (159, 160, 'Sofía Arrate Vargas', 'Lumbalgia', '2024-09-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (160, 161, 'Mauricio Lucena Consalvi', 'Trombosis', '2025-12-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (161, 162, 'Andrea Colina Zapata', 'Trastorno de ansiedad generalizada', '2025-05-13');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (162, 163, 'Nora Torres Zapata', 'EPOC (Enfermedad Pulmonar Obstructiva Crónica)', '2025-04-21');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (163, 164, 'Victor Bautista Cabrera', 'Osteoporosis', '2025-06-14');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (164, 165, 'Esther Campo Quintana', 'Colitis ulcerosa', '2024-06-15');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (165, 166, 'Zulay Correa Bautista', 'Tétanos', '2024-11-09');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (166, 167, 'Laura Baron Cruz', 'Reflujo gastroesofágico (ERGE)', '2024-08-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (167, 168, 'Bernarda Causado Báez', 'Miomatosis uterina', '2024-08-18');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (168, 169, 'José Guerrero Villegas', 'Osteoartritis', '2025-11-20');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (169, 170, 'Eugenio Quintana Cantillo', 'Hipercolesterolemia', '2025-12-27');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (170, 171, 'Rubén Sierra Rodríguez', 'Escabiosis (sarna)', '2024-02-28');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (171, 172, 'Irene Burgos Gómez', 'Colecistitis', '2025-01-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (172, 173, 'Damián Caraballo Lozano', 'Hernia discal', '2024-03-07');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (173, 174, 'Gonzalo Benitez Murillo', 'Dispepsia funcional', '2025-12-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (174, 175, 'Olga Ortega Peña', 'Insuficiencia respiratoria baja', '2025-05-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (175, 176, 'Sebastián Colina Cárdenas', 'Insomnio', '2024-01-12');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (176, 177, 'Adriana Salinas Zambrano', 'COVID-19', '2024-04-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (177, 178, 'Jacobo Rangel Bandres', 'Enfermedad de Parkinson', '2025-04-22');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (178, 179, 'Concepción Contreras Duarte', 'Hepatitis B', '2025-04-05');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (179, 180, 'Fausto Cisneros Zambrano', 'Asma', '2024-09-24');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (180, 181, 'Felipe Calles Pereira', 'Hepatitis B', '2025-02-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (181, 182, 'Yolanda Romero Bustamante', 'Tétanos', '2025-03-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (182, 183, 'Benjamín Quintero Correa', 'Úlcera gástrica', '2025-04-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (183, 184, 'Julian Reyes Campo', 'Insuficiencia respiratoria baja', '2024-04-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (184, 185, 'Emanuel Pereira Marques', 'VIH/SIDA', '2024-09-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (185, 186, 'Teodoro Escobar Marcano', 'Diabetes tipo 2', '2024-05-19');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (186, 187, 'Verónica Méndez Villalobos', 'Fibromialgia', '2024-11-18');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (187, 188, 'Valeria Izquierdo Palma', 'Bronquitis', '2025-05-14');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (188, 189, 'Ruth Lucena Cardona', 'EPOC (Enfermedad Pulmonar Obstructiva Crónica)', '2025-12-22');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (189, 190, 'Susana Mejía Celis', 'Otitis', '2025-12-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (190, 191, 'Gladys Bernal Olivo', 'Depresión', '2024-03-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (191, 192, 'Julia Herrera Baron', 'Cáncer de próstata', '2025-09-15');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (192, 193, 'Héctor Flores Cicero', 'Otitis', '2025-10-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (193, 194, 'Petra González López', 'Varicela', '2025-03-27');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (194, 195, 'Adriana Arévalo Díaz', 'Obesidad', '2024-10-13');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (195, 196, 'Valeria Cabrera Marques', 'Zoster (culebrilla)', '2025-12-29');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (196, 197, 'Ignacio Miranda Gutiérrez', 'Endometriosis', '2025-06-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (197, 198, 'Carlos Izquierdo Arrate', 'Cáncer de próstata', '2024-05-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (198, 199, 'Génesis Barreto Quiroz', 'Hepatitis C', '2024-03-13');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (199, 200, 'Leonardo Salazar Castro', 'Resfriado común', '2025-07-05');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (200, 201, 'Joaquín Casas Barboza', 'Insomnio', '2025-10-09');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (201, 202, 'Carlos Zambrano Cruz', 'Hipotiroidismo', '2025-11-11');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (202, 203, 'Mario Miranda Valencia', 'Rubéola', '2024-10-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (203, 204, 'María Ospina Brito', 'Migraña', '2024-10-12');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (204, 205, 'Fidel Téllez Valera', 'Artritis', '2024-09-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (205, 206, 'Catalina Ramos Murillo', 'Fiebre tifoidea', '2024-02-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (206, 207, 'Adrián García Contreras', 'Anemia', '2025-02-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (207, 208, 'Ramiro Valencia Yépez', 'Varicela', '2024-06-05');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (208, 209, 'Emma Cadenas Arguello', 'VIH/SIDA', '2025-12-07');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (209, 210, 'Patricia Colmenares Gómez', 'Hipotiroidismo', '2025-11-07');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (210, 211, 'Matilde Serrano Bermúdez', 'Osteoartritis', '2024-05-11');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (211, 212, 'Fidel Ortega Suárez', 'Miomatosis uterina', '2025-10-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (212, 213, 'Julia Gutiérrez Jaimes', 'Malaria', '2024-07-23');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (213, 214, 'Guillermo Ramos Soto', 'Lupus', '2025-11-12');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (214, 215, 'Matilde Velásquez Navarro', 'Virus del Papiloma Humano (VPH)', '2024-08-27');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (215, 216, 'Francisca Carrillo Delgado', 'Esquizofrenia', '2024-10-28');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (216, 217, 'Ulises Palacios Causado', 'Resfriado común', '2024-12-29');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (217, 218, 'Elvira Bernal Cerrada', 'Faringitis', '2025-07-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (218, 219, 'Rigoberto Marín Álvarez', 'Malaria', '2025-10-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (219, 220, 'Samuel Reyes Villegas', 'Diarrea', '2025-12-21');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (220, 221, 'Oscar Santana Navarro', 'Urticaria', '2025-02-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (221, 222, 'Elvira Vargas López', 'Infección urinaria', '2024-12-05');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (222, 223, 'Patricio Bolivar Mejía', 'Lues connatal', '2024-04-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (223, 224, 'Gloria Caraballo Bandres', 'Demencia', '2025-02-19');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (224, 225, 'Javier Torres Olivo', 'Enfermedad de Ménière', '2024-12-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (225, 226, 'Lourdes Medina Bautista', 'Asma', '2025-04-14');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (226, 227, 'Consuelo Colina Burgos', 'Zoster (culebrilla)', '2025-01-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (227, 228, 'Ulises Trejo Casas', 'Osteoporosis', '2024-10-06');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (228, 229, 'Daniela Ramos Valenzuela', 'Vértigo', '2025-12-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (229, 230, 'Consuelo Ramírez Rivas', 'Endometriosis', '2024-01-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (230, 231, 'Daniela Toro Celis', 'Psoriasis', '2024-07-23');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (231, 232, 'Elias Palma Salcedo', 'Síncope', '2025-01-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (232, 233, 'Manuela Gil Bernal', 'Rubéola', '2024-10-14');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (233, 234, 'René Álvarez Galindo', 'Virus del Papiloma Humano (VPH)', '2025-12-18');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (234, 235, 'Ismael Aranda Calles', 'Alzheimer', '2025-12-16');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (235, 236, 'Nelly Arévalo Aular', 'Diabetes tipo 1', '2024-08-17');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (236, 237, 'Paula Pérez Navia', 'Cáncer de mama', '2025-10-11');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (237, 238, 'Fermín Asuaje Márquez', 'Enfermedad de Crohn', '2025-02-21');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (238, 239, 'Noelia Campos Castillo', 'Diabetes tipo 2', '2025-01-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (239, 240, 'Juana Colmenares Vargas', 'Enfermedad de Parkinson', '2025-06-07');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (240, 241, 'Mateo Véliz Uribe', 'Asma', '2024-12-13');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (241, 242, 'Xiomara González Correa', 'Diabetes tipo 1', '2024-01-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (242, 243, 'Ricardo Villegas Olivo', 'Dengue', '2025-01-31');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (243, 244, 'Rosa María Causado Brito', 'Enfermedad de Parkinson', '2025-01-29');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (244, 245, 'Baltazar Yépez Trujillo', 'Cistitis', '2024-06-13');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (245, 246, 'Fidel Medina Campo', 'Resfriado común', '2024-07-11');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (246, 247, 'Fidel Véliz Guevara', 'Síncope', '2024-05-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (247, 248, 'Luis Uribe Ibarra', 'Pancreatitis', '2024-07-05');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (248, 249, 'Petra Vega Caraballo', 'Enfermedad de Parkinson', '2024-06-28');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (249, 250, 'Rafael Paz Caraballo', 'Difteria', '2024-07-31');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (250, 251, 'Patricio Mora Arroyo', 'Lues connatal', '2025-03-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (251, 252, 'María Mejía Zambrano', 'Vértigo', '2024-09-09');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (252, 253, 'Bernardo Pinto Flores', 'Dispepsia funcional', '2025-08-23');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (253, 254, 'Luis Miranda Lucena', 'Dengue', '2025-05-22');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (254, 255, 'Lidia Contreras Arias', 'Ansiedad', '2025-03-10');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (255, 256, 'Andrea Gómez Marcano', 'Zoster (culebrilla)', '2024-01-13');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (256, 257, 'Silvia Borjas Aranda', 'Hipertiroidismo', '2024-03-06');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (257, 258, 'Gloria Moreno Caraballo', 'Cáncer de colon', '2025-07-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (258, 259, 'Víctor Navia Granados', 'Miopía', '2025-04-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (259, 260, 'Juana Brito Consalvi', 'Obesidad', '2024-01-29');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (260, 261, 'Miriam Maldonado Barros', 'Endometriosis', '2025-08-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (261, 262, 'Catalina Baron Fernández', 'Colitis ulcerosa', '2025-10-08');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (262, 263, 'Yajaira Vidal Pereira', 'Tétanos', '2024-10-07');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (263, 264, 'Xiomara Ramos Caraballo', 'Esclerosis múltiple', '2025-03-20');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (264, 265, 'Francisca Avila Suárez', 'Asma', '2024-06-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (265, 266, 'Adrián Casas Cedeno', 'Urticaria', '2024-04-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (266, 267, 'Jimena Cabrera Vega', 'Cáncer de colon', '2024-05-11');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (267, 268, 'Yosmary León Soto', 'Cáncer de mama', '2024-06-28');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (268, 269, 'Camila Marcano Palacios', 'Ansiedad', '2024-12-01');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (269, 270, 'Milagros Arjona Trujillo', 'Urticaria', '2024-10-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (270, 271, 'Andrés Calles Cordero', 'Trastorno de ansiedad generalizada', '2025-11-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (271, 272, 'Benjamín Arrate Naranjo', 'Rinitis alérgica', '2024-12-19');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (272, 273, 'Antonieta Gil Valencia', 'Mononucleosis infecciosa', '2024-11-28');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (273, 274, 'Fernanda Maldonado Cano', 'Faringitis', '2025-10-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (274, 275, 'Miriam Bolivar Zambrano', 'Cáncer de mama', '2024-02-14');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (275, 276, 'José Redondo Carvajal', 'Infarto agudo al miocardio', '2025-10-06');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (276, 277, 'Mauricio Calles Henríquez', 'Otitis', '2025-09-09');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (277, 278, 'Ignacio Cordero González', 'Artritis', '2025-10-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (278, 279, 'Bernardo Cicero Zambrano', 'Esclerosis múltiple', '2024-12-14');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (279, 280, 'Saúl Pinto Téllez', 'Cefalea tensional', '2024-10-27');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (280, 281, 'Agustín Arrate Maldonado', 'Intolerancia a la lactosa', '2025-06-20');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (281, 282, 'Zulimar Olivo Vásquez', 'Difteria', '2025-08-14');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (282, 283, 'Martín Consalvi Bermúdez', 'Reflujo gastroesofágico (ERGE)', '2024-01-20');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (283, 284, 'Juana Méndez Granados', 'Estreñimiento', '2024-08-06');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (284, 285, 'Lourdes Quintana Téllez', 'Osteoporosis', '2025-10-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (285, 286, 'Agustín Pereira Zambrano', 'Varicela', '2024-09-18');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (286, 287, 'Elisa Marín Torres', 'Insomnio', '2024-07-20');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (287, 288, 'Emma Quiroz Celis', 'Esquizofrenia', '2024-04-02');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (288, 289, 'Leonardo Arrate Casas', 'Bronquitis', '2025-01-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (289, 290, 'Gladys Bohorquez Delgado', 'Resfriado común', '2025-03-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (290, 291, 'Martín Vidal Silva', 'TDAH en adultos', '2025-06-26');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (291, 292, 'Isaac Arroyo Santana', 'Cáncer de mama', '2024-02-25');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (292, 293, 'Aarón Barros Trejo', 'Hipertensión arterial', '2024-04-13');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (293, 294, 'Rita Paz Granados', 'Tétanos', '2024-05-20');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (294, 295, 'Lucía Yánez Padilla', 'Fiebre tifoidea', '2025-10-03');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (295, 296, 'René Jaimes Figueroa', 'Esquizofrenia', '2025-11-04');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (296, 297, 'Miguel Rosales Varela', 'Sarampión', '2024-06-10');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (297, 298, 'Luisana Silva Castillo', 'Apendicitis', '2024-09-30');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (298, 299, 'Samuel Villegas Ibarra', 'Migraña', '2025-09-23');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (299, 300, 'Fermín Flores Delgado', 'COVID-19', '2025-09-19');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (300, 301, 'Agustín Romero Marín', 'Virus del Papiloma Humano (VPH)', '2025-01-15');
COMMIT;

-- TOTAL DE REGISTROS DE MORBILIDAD GENERADOS: 300
