BEGIN TRANSACTION;
-- --------------------------------------------------------------------------------------
-- SCRIPT 03: REGISTROS FINALES DE MORBILIDAD
-- Inserta 300 registros en morbilidad usando la secuencia de IDs generada en el SCRIPT 02.
-- --------------------------------------------------------------------------------------
DELETE FROM morbilidad;
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (1, 2, 'Daniel Moreno Bohorquez', 'Trastorno bipolar', '09/02/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (2, 3, 'Esteban Peraza Calderón', 'Osteoporosis', '24/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (3, 4, 'Noé Avila Ramírez', 'TDAH en adultos', '08/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (4, 5, 'Jacobo Castillo García', 'Rubéola', '18/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (5, 6, 'Beatriz Abreu Zapata', 'Leucemia', '13/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (6, 7, 'Yosmary Marques Maldonado', 'Dengue', '16/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (7, 8, 'Yajaira Lozano Quiroz', 'Enfermedad de Ménière', '20/07/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (8, 9, 'Clara Sandoval Bolivar', 'Trombosis', '24/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (9, 10, 'Mercedes Barboza Lara', 'Lumbalgia', '17/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (10, 11, 'Xiomara Valenzuela Briceño', 'Estreñimiento', '17/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (11, 12, 'Francisca Mendoza Asuaje', 'Diabetes tipo 2', '06/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (12, 13, 'Fermín Salinas Salas', 'Otitis', '10/10/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (13, 14, 'Marco Bermúdez González', 'Fiebre amarilla', '26/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (14, 15, 'Saúl Bolivar Núñez', 'Migraña', '02/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (15, 16, 'Marta Jiménez Cadenas', 'Trombosis', '09/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (16, 17, 'Julio Cordero Pérez', 'Retinopatía diabética', '29/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (17, 18, 'Ramón Jiménez Abreu', 'Estreñimiento', '08/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (18, 19, 'Dolores Benitez Cicero', 'Hernia discal', '19/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (19, 20, 'Claudia Quiñones Bolivar', 'Faringitis', '28/07/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (20, 21, 'Leonardo Figueroa Peña', 'Esquizofrenia', '26/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (21, 22, 'Génesis Báez Lozano', 'Diarrea', '06/08/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (22, 23, 'César Romero Causado', 'Cirrosis hepática', '25/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (23, 24, 'Ángel Serrano Campo', 'Otitis', '24/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (24, 25, 'Camila Cicero Avila', 'Infarto agudo al miocardio', '02/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (25, 26, 'Joaquín Calles Arias', 'TDAH en adultos', '23/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (26, 27, 'Ismael Cardona Quintero', 'Hernia discal', '02/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (27, 28, 'Fidel Serrano Marín', 'Tétanos', '05/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (28, 29, 'Beatriz Henríquez Briceño', 'Hepatitis B', '15/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (29, 30, 'Enrique Arguello Figueroa', 'Obstrucción intestinal', '25/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (30, 31, 'Marta Vásquez Chávez', 'Tuberculosis', '24/08/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (31, 32, 'Eduardo Calderón Yépez', 'Gripe (influenza)', '16/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (32, 33, 'Josefina Cerrada Báez', 'Reflujo gastroesofágico (ERGE)', '28/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (33, 34, 'Julio Calles Cárdenas', 'Zoster (culebrilla)', '31/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (34, 35, 'MariÁngel Barreto Henríquez', 'Apendicitis', '12/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (35, 36, 'Catalina Borjas Rivas', 'Retinopatía diabética', '23/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (36, 37, 'Guillermo Zabala Arcila', 'Insuficiencia respiratoria baja', '28/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (37, 38, 'Olga Prieto Colmenares', 'Pancreatitis', '26/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (38, 39, 'Gloria Acosta Palacios', 'Miomatosis uterina', '03/02/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (39, 40, 'Inés Quintana Benitez', 'Hepatitis A', '14/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (40, 41, 'Yosmary Medina Salas', 'EPOC (Enfermedad Pulmonar Obstructiva Crónica)', '30/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (41, 42, 'Roberto Silva Bello', 'Hepatitis A', '06/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (42, 43, 'Víctor Calles Mora', 'Fiebre amarilla', '14/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (43, 44, 'Ignacio Cordero Colina', 'COVID-19', '18/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (44, 45, 'Miguel Reyes Sánchez', 'Tétanos', '17/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (45, 46, 'Bernarda Alvarado Valdez', 'Insomnio', '11/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (46, 47, 'Roberto Bello Salazar', 'Pielonefritis', '24/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (47, 48, 'Julio Trejo Aular', 'Osteoartritis', '01/02/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (48, 49, 'Eduardo Zapata López', 'Diarrea', '06/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (49, 50, 'MariÁngel Ospina Márquez', 'Cefalea tensional', '14/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (50, 51, 'Yusmary Zabala Bautista', 'Otitis', '03/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (51, 52, 'Isaac Uribe Briceño', 'Hipertensión arterial', '16/07/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (52, 53, 'Lidia Zambrano Cabrera', 'Fiebre tifoidea', '12/08/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (53, 54, 'Génesis Carrillo Toro', 'Hernia discal', '02/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (54, 55, 'Gabriela Soto Figueroa', 'Diabetes tipo 2', '26/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (55, 56, 'Patricio Velásquez Cardona', 'Tétanos', '06/10/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (56, 57, 'Erick Mejía Zambrano', 'Fiebre tifoidea', '27/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (57, 58, 'Sebastián Del Castillo Toro', 'Enfermedad de Parkinson', '06/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (58, 59, 'Yusbely Abreu Prieto', 'Insuficiencia respiratoria baja', '16/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (59, 60, 'Edith Estrada Rivera', 'Obesidad', '12/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (60, 61, 'Javier Bohorquez Palma', 'Enfermedad de Ménière', '28/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (61, 62, 'Oriana Mora Arroyo', 'Varicela', '12/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (62, 63, 'Mario Quiñones Bustamante', 'Obesidad', '13/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (63, 64, 'Fernando Aular Arévalo', 'Hipertiroidismo', '10/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (64, 65, 'Elias González Rojas', 'Insuficiencia respiratoria baja', '18/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (65, 66, 'Yulimar Vásquez Bohorquez', 'Depresión', '05/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (66, 67, 'Gonzalo Castro Palacios', 'Esquizofrenia', '05/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (67, 68, 'Juana Bautista Rojas', 'Bronquitis', '28/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (68, 69, 'Rubén Rangel Cicero', 'EPOC (Enfermedad Pulmonar Obstructiva Crónica)', '07/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (69, 70, 'Gregorio Pulido Roldán', 'Esclerosis múltiple', '19/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (70, 71, 'Mauricio Sandoval Quiñones', 'Cirrosis hepática', '12/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (71, 72, 'Ninoska Toro Cisneros', 'Virus del Papiloma Humano (VPH)', '11/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (72, 73, 'Eduardo Ruiz Velásquez', 'Hepatitis B', '05/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (73, 74, 'Elias Ramírez Ortiz', 'Insomnio', '14/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (74, 75, 'Manuela Zambrano Cano', 'Toxoplasmosis', '25/10/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (75, 76, 'Víctor Velásquez Rosales', 'Gripe (influenza)', '17/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (76, 77, 'Jacobo Toro Quintero', 'Pielonefritis', '14/10/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (77, 78, 'Nicolás Fernández Rivera', 'Hepatitis B', '09/10/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (78, 79, 'Julio Bravo Acosta', 'Varicela', '29/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (79, 80, 'Esteban Bautista Arteaga', 'Estreñimiento', '04/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (80, 81, 'Elvira Márquez Suárez', 'Toxoplasmosis', '15/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (81, 82, 'Gabriel Rincón Contreras', 'Hipotiroidismo', '30/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (82, 83, 'Mario Cicero Aguilar', 'Faringitis', '24/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (83, 84, 'Rigoberto Arroyo Arguello', 'Gripe (influenza)', '09/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (84, 85, 'Julia Silva Peña', 'Tétanos', '31/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (85, 86, 'Sofía Consalvi Márquez', 'Colitis ulcerosa', '29/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (86, 87, 'Alejandro Campos Márquez', 'Estreñimiento', '22/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (87, 88, 'María Chávez Ortiz', 'Toxoplasmosis', '28/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (88, 89, 'Alberto Sandoval Naranjo', 'Hepatitis A', '20/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (89, 90, 'Teresa Chávez Ruiz', 'Miomatosis uterina', '23/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (90, 91, 'Fernando Báez Prieto', 'Migraña', '08/07/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (91, 92, 'Valeria Lucena Velásquez', 'Retinopatía diabética', '27/10/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (92, 93, 'Gregorio Vidal Cordero', 'Migraña', '28/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (93, 94, 'Joaquín Celis Calderón', 'Resfriado común', '18/04/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (94, 95, 'Petra Fernández Ospina', 'Hipotiroidismo', '16/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (95, 96, 'Sofía Colmenares Valenzuela', 'Miopía', '27/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (96, 97, 'Ulises Hernández Villegas', 'Ansiedad', '13/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (97, 98, 'Valentina Aular Sierra', 'Trastorno bipolar', '03/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (98, 99, 'Fidel Cabrera Pereira', 'Insuficiencia respiratoria baja', '31/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (99, 100, 'Ramiro Granados Acosta', 'Resfriado común', '16/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (100, 101, 'Fermín Vega Gallegos', 'Hipertensión arterial', '10/02/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (101, 102, 'Petra Causado Vargas', 'Hipotiroidismo', '26/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (102, 103, 'Jorge Olivo Acosta', 'Urticaria', '22/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (103, 104, 'David Aguilar Lara', 'Miopía', '12/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (104, 105, 'Bernardo Naranjo Causado', 'Hipertensión arterial', '06/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (105, 106, 'Camila Asuaje Bustamante', 'Endometriosis', '18/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (106, 107, 'Rigoberto Murillo Bravo', 'Mononucleosis infecciosa', '28/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (107, 108, 'Petra Jiménez Quiñones', 'Cáncer de mama', '04/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (108, 109, 'Elena Rincón Arismendi', 'Hipertiroidismo', '30/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (109, 110, 'Natalia Arteaga Cedeno', 'Esclerosis múltiple', '27/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (110, 111, 'Armando Fajardo Palacios', 'Apendicitis', '27/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (111, 112, 'Esther Granados Fajardo', 'Hipercolesterolemia', '26/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (112, 113, 'Alicia Quiñones Soto', 'Urticaria', '03/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (113, 114, 'Rocío Reyes Cerrada', 'Esquizofrenia', '05/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (114, 115, 'Raúl Marcano Díaz', 'Síncope', '07/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (115, 116, 'Cecilia Bautista Barrios', 'Rubéola', '03/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (116, 117, 'Milagros Zabala Ortega', 'Esófago de Barrett', '09/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (117, 118, 'Elvira Hernández Serrano', 'Meningitis', '14/10/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (118, 119, 'Irma Cerrada Ortega', 'Dispepsia funcional', '04/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (119, 120, 'Gustavo Maldonado Ortega', 'Hipertiroidismo', '17/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (120, 121, 'Salvador Bermúdez Arias', 'Zoster (culebrilla)', '15/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (121, 122, 'Rodrigo Redondo Jaimes', 'Lumbalgia', '05/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (122, 123, 'Marta Figueroa Valencia', 'Enfermedad de Graves', '09/08/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (123, 124, 'Verónica Santana Zabala', 'Diarrea', '25/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (124, 125, 'Daniela Arjona Restrepo', 'Asma', '17/07/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (125, 126, 'Andrea Fuentes Carvajal', 'Diarrea', '21/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (126, 127, 'Rigoberto López Ramos', 'Obesidad', '06/06/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (127, 128, 'Gonzalo Peña García', 'Neumonía', '18/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (128, 129, 'Amparo Acosta Galindo', 'Lumbalgia', '21/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (129, 130, 'Natalia Carreño Duarte', 'Pancreatitis', '04/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (130, 131, 'Gabriela Carrillo Rivera', 'Cáncer de mama', '25/06/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (131, 132, 'Eugenio González Sandoval', 'Endometriosis', '18/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (132, 133, 'Soledad Valencia Fuentes', 'Rinitis alérgica', '16/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (133, 134, 'Julio Peña Ramos', 'COVID-19', '25/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (134, 135, 'Ronaldo García Báez', 'Alzheimer', '05/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (135, 136, 'Génesis Zambrano Arévalo', 'Diarrea', '07/10/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (136, 137, 'Rigoberto Velásquez Jaimes', 'Tuberculosis', '08/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (137, 138, 'Luisana Báez Paz', 'Obesidad', '06/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (138, 139, 'Silvia Alvarado Sánchez', 'Infarto agudo al miocardio', '27/10/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (139, 140, 'Javier Aranda Valdez', 'Escabiosis (sarna)', '31/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (140, 141, 'Olga Celis Montes', 'Rabia', '16/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (141, 142, 'Elena Zambrano Toro', 'Obesidad', '23/08/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (142, 143, 'Bernarda Bernal Moreno', 'Retinopatía diabética', '25/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (143, 144, 'Patricio Téllez Zapata', 'Endometriosis', '19/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (144, 145, 'Walter Caraballo Martínez', 'Alzheimer', '24/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (145, 146, 'Elena Cisneros Zambrano', 'Gastritis', '12/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (146, 147, 'Oriana Bolivar Arévalo', 'Hepatitis C', '11/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (147, 148, 'Manuela Peraza Rivas', 'Hipertensión arterial', '31/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (148, 149, 'Teresa García Arcila', 'Migraña', '28/06/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (149, 150, 'Joaquín Contreras Mora', 'Osteoartritis', '31/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (150, 151, 'Juana Salinas Paredes', 'Malaria', '31/07/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (151, 152, 'Ronaldo Sánchez Toro', 'Intolerancia a la lactosa', '21/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (152, 153, 'Xiomara Santana Caballero', 'Lues connatal', '25/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (153, 154, 'Gonzalo Peña Guerrero', 'Urticaria', '02/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (154, 155, 'Lucía Pulido Gil', 'Demencia', '08/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (155, 156, 'Beatriz Zambrano Sierra', 'Intolerancia a la lactosa', '17/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (156, 157, 'Elena Vega Chávez', 'Anemia', '22/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (157, 158, 'María Blanco Márquez', 'Otitis', '02/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (158, 159, 'Eva Escobar Ibarra', 'Otitis', '13/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (159, 160, 'Gladys Téllez Parra', 'Tétanos', '22/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (160, 161, 'Alberto Arrate Cano', 'Rinitis alérgica', '06/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (161, 162, 'Ruth Zambrano Carvajal', 'Lupus', '31/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (162, 163, 'Beatriz Hernández Rojas', 'Guillain-Barré (síndrome de)', '10/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (163, 164, 'Cecilia Roldán Paredes', 'Fibromialgia', '27/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (164, 165, 'Claudia Fuentes Cruz', 'Diarrea', '17/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (165, 166, 'Camila Morales Palacios', 'Hepatitis B', '05/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (166, 167, 'Aarón Redondo Zabala', 'Difteria', '28/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (167, 168, 'Mateo Bravo Salas', 'Urticaria', '21/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (168, 169, 'Eduardo Gutiérrez Bustamante', 'Psoriasis', '01/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (169, 170, 'Ignacio Rincón Sandoval', 'Diabetes tipo 2', '14/02/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (170, 171, 'Zulay Gil Paredes', 'Enfermedad de Ménière', '11/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (171, 172, 'Oscar Cisneros Rangel', 'EPOC (Enfermedad Pulmonar Obstructiva Crónica)', '14/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (172, 173, 'Soledad Izquierdo Quiroz', 'Diabetes tipo 2', '11/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (173, 174, 'Elvira Zambrano Rangel', 'Dispepsia funcional', '29/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (174, 175, 'Luisa Maldonado Gil', 'Depresión', '17/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (175, 176, 'Pablo Chávez Marques', 'Reflujo gastroesofágico (ERGE)', '18/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (176, 177, 'Miguel Arroyo Jiménez', 'Enfermedad de Ménière', '16/10/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (176, 177, 'Aarón Caraballo Díaz', 'Enfermedad de Crohn', '06/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (177, 178, 'Salvador León Barrios', 'Retinopatía diabética', '16/08/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (178, 179, 'Raúl Valdez Lara', 'Enfermedad de Parkinson', '18/02/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (180, 181, 'Francisca Rangel Olivo', 'Dengue', '30/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (181, 182, 'Gerardo Sánchez Bustamante', 'Trombosis', '30/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (182, 183, 'Rita Peraza Barros', 'Enfermedad de Ménière', '09/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (182, 183, 'Génesis Arguello Gómez', 'Esquizofrenia', '19/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (184, 185, 'David Vásquez Azocar', 'Trastorno de ansiedad generalizada', '03/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (185, 186, 'Ángela Marcano Fuentes', 'Gastritis', '21/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (185, 186, 'Gregorio Arteaga Trejo', 'Miopía', '17/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (186, 187, 'Óscar Carreño Téllez', 'Mononucleosis infecciosa', '18/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (187, 188, 'Lucía Moreno Arroyo', 'Depresión', '28/04/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (189, 190, 'Lilian Pinto Pinto', 'Insomnio', '28/07/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (190, 191, 'Rodrigo Mejía Cortez', 'Enfermedad de Crohn', '31/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (190, 191, 'Valentín Rivera Hernández', 'Hipercolesterolemia', '10/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (192, 193, 'Rosa Valdez Duarte', 'Hipotiroidismo', '31/10/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (193, 194, 'Yusbely Betancourt Benitez', 'Diabetes tipo 1', '06/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (194, 195, 'Ramiro Soto Varela', 'Artritis', '22/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (195, 196, 'Irma Trujillo Correa', 'Escabiosis (sarna)', '27/04/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (196, 197, 'Marta Briceño Arias', 'Cistitis', '19/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (197, 198, 'Petra Lara Quiñones', 'Cistitis', '28/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (197, 198, 'Raúl Cisneros Cabrera', 'TDAH (Trastorno por Déficit de Atención e Hiperactividad)', '24/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (198, 199, 'Bernarda Parra Duarte', 'Resfriado común', '24/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (200, 201, 'Yolanda Celis Valdez', 'Hipotiroidismo', '02/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (201, 202, 'Matilde Cárdenas Aular', 'Reflujo gastroesofágico (ERGE)', '21/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (202, 203, 'Alejandra Bustamante Zambrano', 'Difteria', '24/08/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (203, 204, 'Lidia Zambrano Prieto', 'Pancreatitis', '07/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (204, 205, 'Olivia Valera Arias', 'Difteria', '12/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (205, 206, 'Oscar Ortiz Lara', 'Enfermedad de Ménière', '13/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (206, 207, 'Milagros Peña Vidal', 'Miopía', '12/02/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (207, 208, 'Luis Barboza Ruiz', 'Cefalea tensional', '26/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (208, 209, 'Fernando Duarte Colmenares', 'Tétanos', '20/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (209, 210, 'Concepción Galindo Vargas', 'Dengue', '04/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (210, 211, 'Olivia Vásquez Redondo', 'VIH/SIDA', '19/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (211, 212, 'Agustín Chávez Paz', 'Insuficiencia respiratoria baja', '18/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (212, 213, 'Camila Navarro Velásquez', 'Síncope', '09/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (213, 214, 'Francisca Granados Correa', 'Dispepsia funcional', '01/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (214, 215, 'Valentina León Caballero', 'Hipercolesterolemia', '22/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (215, 216, 'Marco Arguello Ospina', 'Lumbalgia', '05/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (216, 217, 'Cristóbal Zambrano Campos', 'Urticaria', '11/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (217, 218, 'Ana Peraza Véliz', 'Lupus', '18/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (218, 219, 'Mariana Navia Marques', 'Artritis', '19/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (219, 220, 'Margarita Arismendi Mejía', 'Rinitis alérgica', '21/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (220, 221, 'Natalia Arcila Bernal', 'Cáncer de colon', '15/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (221, 222, 'Yolanda Jiménez Trejo', 'Virus del Papiloma Humano (VPH)', '21/10/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (222, 223, 'Marta Galindo Quintana', 'Enfermedad de Ménière', '09/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (223, 224, 'Leonardo Gil Casas', 'TDAH (Trastorno por Déficit de Atención e Hiperactividad)', '24/10/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (224, 225, 'Daniel Gallegos Méndez', 'Colecistitis', '23/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (225, 226, 'Laura Medina Cicero', 'Obesidad', '01/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (226, 227, 'Eduardo Maldonado Trejo', 'Osteoartritis', '16/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (227, 228, 'Héctor Colmenares Cantillo', 'Estreñimiento', '14/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (228, 229, 'Fernando Salcedo Caraballo', 'Gastritis', '11/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (229, 230, 'Nelly Velásquez Medina', 'Insomnio', '01/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (230, 231, 'Alejandra Cortez Maldonado', 'Dengue', '18/02/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (231, 232, 'Valentina Guerrero Prieto', 'Sordera', '27/06/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (232, 233, 'Teresa Cortez Bermúdez', 'Dengue', '08/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (233, 234, 'Julio Rodríguez Causado', 'Trastorno bipolar', '28/07/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (234, 235, 'Jesús Torres Pulido', 'Fiebre tifoidea', '02/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (235, 236, 'Sofía Barreto Briceño', 'Toxoplasmosis', '10/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (236, 237, 'Walter Navia Carvajal', 'TDAH en adultos', '30/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (237, 238, 'Lismar Jaimes López', 'Hepatitis B', '02/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (238, 239, 'Alba Reyes Salcedo', 'Bronquitis', '22/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (239, 240, 'Eugenio Carreño Redondo', 'Rabia', '02/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (240, 241, 'Lismar Del Castillo Serrano', 'Esclerosis múltiple', '05/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (241, 242, 'Daniela Abreu Yánez', 'Infección urinaria', '13/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (242, 243, 'Gregorio López Padilla', 'Cáncer de próstata', '09/07/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (243, 244, 'Bernardo Fajardo Gutiérrez', 'Enfermedad de Crohn', '22/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (244, 245, 'Josefina Arismendi Rangel', 'Lumbalgia', '14/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (245, 246, 'María Ibarra León', 'VIH/SIDA', '22/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (246, 247, 'Matilde Romero Gil', 'Hipertiroidismo', '09/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (247, 248, 'Patricia Arévalo Barros', 'Gripe (influenza)', '15/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (248, 249, 'Roberto Sandoval Ramírez', 'Intolerancia a la lactosa', '13/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (249, 250, 'Carmen Ibarra Zambrano', 'Miopía', '11/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (250, 251, 'Catalina Causado Naranjo', 'Depresión', '08/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (251, 252, 'Andrés Zambrano Rivera', 'Trastorno bipolar', '08/10/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (252, 253, 'Emma Bohorquez Toro', 'Sarampión', '12/02/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (253, 254, 'Hugo Ortega Restrepo', 'Dengue', '12/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (254, 255, 'Damián Colmenares Ruiz', 'EPOC (Enfermedad Pulmonar Obstructiva Crónica)', '17/10/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (255, 256, 'Esther Bautista Avila', 'Gastritis', '13/01/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (256, 257, 'Salvador Valencia Barros', 'Cefalea tensional', '31/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (257, 258, 'Camila Celis Pérez', 'Cáncer de colon', '11/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (258, 259, 'Carlos Trejo Moreno', 'Cáncer de colon', '15/10/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (259, 260, 'Fernanda Cadenas Cisneros', 'Gripe (influenza)', '26/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (260, 261, 'Irma Sierra Lucena', 'Toxoplasmosis', '19/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (261, 262, 'Mayerling Betancourt Villegas', 'Esclerosis múltiple', '26/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (262, 263, 'Alonso Zambrano Zapata', 'COVID-19', '15/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (263, 264, 'Leonardo Cerrada Vidal', 'Neumonía', '13/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (264, 265, 'Mario Guerra Consalvi', 'Colitis ulcerosa', '26/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (265, 266, 'Emilio Lara Cardona', 'Enfermedad de Parkinson', '14/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (266, 267, 'Antonio Vargas Consalvi', 'Rinitis alérgica', '13/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (267, 268, 'Ignacio Cedeno Cruz', 'Varicela', '17/07/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (268, 269, 'Joaquín Marques Moreno', 'Lues connatal', '11/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (269, 270, 'Yusmary Moreno Reyes', 'Virus del Papiloma Humano (VPH)', '23/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (270, 271, 'Emanuel Montes Vargas', 'Urticaria', '03/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (271, 272, 'Pablo Palacios Pinto', 'Intolerancia a la lactosa', '05/12/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (272, 273, 'Enrique Quiñones Mora', 'Fiebre tifoidea', '04/12/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (273, 274, 'Matilde Restrepo Marín', 'Diabetes tipo 1', '15/07/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (274, 275, 'Joaquín Gallegos Olivo', 'Fiebre tifoidea', '08/03/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (274, 275, 'Cristóbal Prieto Barros', 'Depresión', '04/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (276, 277, 'Yusbely Pérez Bautista', 'Hepatitis A', '27/09/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (277, 278, 'Josefina Cantillo Sierra', 'Lupus', '06/06/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (278, 279, 'Paula Santana Quiroz', 'Otitis', '24/11/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (279, 280, 'Catalina Cordero Montes', 'Urticaria', '23/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (279, 280, 'Luisa Cedeno Redondo', 'Síncope', '24/10/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (281, 282, 'Valeria Cardona Fuentes', 'Zoster (culebrilla)', '21/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (282, 283, 'Baltazar Zambrano Montes', 'Hipotiroidismo', '29/09/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (283, 284, 'Sebastián Fuentes Caballero', 'Endometriosis', '20/11/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (284, 285, 'Mariana Mendoza Palma', 'Insomnio', '04/06/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (285, 286, 'Margarita Casas Causado', 'Malaria', '03/02/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (286, 287, 'Saúl Barreto Barboza', 'Endometriosis', '29/05/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (287, 288, 'Gabriela Bohorquez Pérez', 'Diabetes tipo 1', '05/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (287, 288, 'Raúl Brito Carvajal', 'Apendicitis', '13/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (288, 289, 'César León Valdez', 'Miopía', '18/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (290, 291, 'Noé Baron Delgado', 'Insuficiencia respiratoria baja', '15/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (290, 291, 'Roberto Acosta Romero', 'Vértigo', '23/01/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (291, 292, 'Rita Roldán Varela', 'Guillain-Barré (síndrome de)', '09/07/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (293, 294, 'Samuel Cicero Barros', 'COVID-19', '15/08/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (293, 294, 'Andrés Lara Cicero', 'Esquizofrenia', '21/03/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (295, 296, 'Cristian Jaimes Bautista', 'Obstrucción intestinal', '26/04/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (296, 297, 'Natalia Colina Barreto', 'Tuberculosis', '28/05/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (297, 298, 'Irma López Figueroa', 'Cefalea tensional', '12/10/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (298, 299, 'Diego Uribe Arismendi', 'Tuberculosis', '24/06/2024');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (299, 300, 'Fermín Bautista Henríquez', 'Enfermedad de Crohn', '29/04/2025');
INSERT INTO morbilidad (id_paciente, id_direccion_hogar, nombres_apellidos, diagnostico, fecha_registro_formulario) VALUES (300, 301, 'Baltazar Bautista Sierra', 'Insuficiencia respiratoria baja', '12/03/2024');
COMMIT;

-- TOTAL DE REGISTROS DE MORBILIDAD GENERADOS: 300
