BEGIN TRANSACTION;
-- --------------------------------------------------------------------------------------
-- SCRIPT 05: INSERCIÓN EN MORTALIDAD NEONATAL (3 Tablas en Cascada)
-- --------------------------------------------------------------------------------------

-- 1. INSERTAR ENTIDADES PACIENTE (Para obtener id_paciente, clave para mortalidad)
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);

-- 2. INSERTAR ENTIDADES DIRECCIÓN (Para obtener id_direccion, clave para mortalidad)
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 16, Sector Los Ángeles.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 35, Sector Casco Central.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 70, Sector Paraíso 2.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 27, Sector Pueblo Nuevo Sur.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 85, Sector Pedro Camejo.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 19, Sector Las Villas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 94, Sector Paraíso 1.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 55, Sector Pueblo Nuevo Sur.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 94, Sector Los Ángeles.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 69, Sector Bicentenario.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 61, Sector Las Villas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 87, Sector Simón Bolívar.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 77, Sector Simón Bolívar.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 5, Sector Paraíso 1.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 42, Sector Valmore Rodríguez.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 61, Sector San José.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 96, Sector Cementerio.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 18, Sector Colinas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 25, Sector Colinas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 68, Sector 19 de Marzo.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 17, Sector Simón Bolívar.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 79, Sector Paraíso 1.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 86, Sector Cementerio.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 48, Sector Pedro Camejo.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 79, Sector Campo Alegre.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 6, Sector Pueblo Nuevo Sur.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 87, Sector Campo Oficina.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 70, Sector Pueblo Nuevo Sur.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 73, Sector San José.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 75, Sector Casco Central.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 36, Sector San José.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 33, Sector Campo Oficina.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 39, Sector Central.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 69, Sector Casco Central.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 80, Sector La Floresta.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 61, Sector Las Villas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 11, Sector Las Villas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 12, Sector Los Ángeles.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 94, Sector Campo Alegre.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 36, Sector Campo Oficina.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 81, Sector Casco Central.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 41, Sector Pueblo Nuevo Sur.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 68, Sector Paraíso 2.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 93, Sector Bicentenario.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 57, Sector Casco Central.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 33, Sector Campo Alegre.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 50, Sector Las Villas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 28, Sector La Floresta.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 83, Sector Paraíso 1.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 33, Sector Paraíso 1.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));

-- 3. INSERTAR MORTALIDAD (Principal) y MORTALIDAD_NEONATAL (Detalle)
DELETE FROM mortalidad_neonatal;
DELETE FROM mortalidad;
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 49, '48929271', 'Elias Hernández Castro', '13/09/2025', '13/09/2025', '12:32:00', '28/09/2025', '11:21:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 16, Sector Los Ángeles.' LIMIT 1), 'distensión abdominal, sangre en heces, vómitos biliosos, letargo, fiebre.', 'Enterocolitis necrotizante', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Isabel Quintero Olivo', '12:32:00', '37', '2.96', '43.28');
-- IDx Neonatal: 10000 : 20000
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 48, '18601869', 'Nora Baron Palacios', '24/09/2024', '24/09/2024', '14:12:00', '13/10/2024', '16:52:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 35, Sector Casco Central.' LIMIT 1), 'lesiones vesiculares, fiebre, letargo, convulsiones, hepatitis.', 'Infección por herpes neonatal', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Beatriz Baron Bravo', '14:12:00', '25', '2.08', '36.48');
-- IDx Neonatal: 10001 : 20001
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 47, '59068634', 'Elena Soto Guerra', '24/11/2024', '24/11/2024', '13:01:00', '12/12/2024', '15:20:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 70, Sector Paraíso 2.' LIMIT 1), 'dificultad para respirar, succión débil, hipotermia, apnea, bajo peso, inmadurez pulmonar.', 'Prematuridad', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Irene Ruiz Abreu', '13:01:00', '26', '2.92', '40.81');
-- IDx Neonatal: 10002 : 20002
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 46, '87802338', 'Fermín Colmenares Paredes', '07/03/2025', '07/03/2025', '17:14:00', '02/04/2025', '01:23:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 27, Sector Pueblo Nuevo Sur.' LIMIT 1), 'dificultad respiratoria progresiva, quejido espiratorio, retracciones, cianosis.', 'Enfermedad de membrana hialina', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Bernarda Barboza Moreno', '17:14:00', '41', '3.34', '36.86');
-- IDx Neonatal: 10003 : 20003
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 45, '77043007', 'Isabel Estrada Quiroz', '22/10/2025', '22/10/2025', '13:30:00', '12/11/2025', '15:06:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 85, Sector Pedro Camejo.' LIMIT 1), 'dificultad respiratoria, cianosis, taquipnea, quejido, retracciones.', 'Síndrome de aspiración meconial', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Gladys Brito Zambrano', '13:30:00', '24', '2.08', '40.93');
-- IDx Neonatal: 10004 : 20004
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 44, '36089212', 'Francisca Fuentes Abreu', '16/04/2024', '16/04/2024', '07:45:00', '21/04/2024', '06:38:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 19, Sector Las Villas.' LIMIT 1), 'fontanela abombada, macrocefalia, vómitos, irritabilidad, mirada en sol poniente.', 'Hidrocefalia', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Daniela Rojas Cordero', '07:45:00', '22', '2.97', '41.82');
-- IDx Neonatal: 10005 : 20005
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 43, '26658166', 'Génesis Paredes Quiroz', '17/01/2024', '17/01/2024', '19:22:00', '12/02/2024', '19:36:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 94, Sector Paraíso 1.' LIMIT 1), 'hipotensión, taquicardia, piel moteada, letargo, oliguria.', 'Shock séptico', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Verónica Rangel León', '19:22:00', '33', '2.17', '49.49');
-- IDx Neonatal: 10006 : 20006
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 42, '91214165', 'Rodrigo Vargas Urdaneta', '10/06/2024', '10/06/2024', '14:07:00', '30/06/2024', '07:51:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 55, Sector Pueblo Nuevo Sur.' LIMIT 1), 'cianosis, taquipnea, soplo cardíaco, dificultad respiratoria.', 'Hipertensión pulmonar persistente', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Olga Roldán Aranda', '14:07:00', '20', '2.41', '35.11');
-- IDx Neonatal: 10007 : 20007
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 41, '51399799', 'Berta Bandres Yánez', '04/07/2024', '04/07/2024', '21:12:00', '28/07/2024', '07:21:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 94, Sector Los Ángeles.' LIMIT 1), 'dificultad para respirar, succión débil, hipotermia, apnea, bajo peso, inmadurez pulmonar.', 'Prematuridad', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Ninoska Arroyo Carvajal', '21:12:00', '42', '2.02', '43.1');
-- IDx Neonatal: 10008 : 20008
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 40, '14062639', 'Daniela Carrillo Santana', '12/10/2025', '12/10/2025', '06:07:00', '25/10/2025', '03:02:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 69, Sector Bicentenario.' LIMIT 1), 'lesiones vesiculares, fiebre, letargo, convulsiones, hepatitis.', 'Infección por herpes neonatal', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Ruth Jiménez Fernández', '06:07:00', '26', '2.3', '51.07');
-- IDx Neonatal: 10009 : 20009
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 39, '20382232', 'Claudia Villalobos Arismendi', '31/10/2024', '31/10/2024', '03:15:00', '05/11/2024', '06:19:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 61, Sector Las Villas.' LIMIT 1), 'hematomas, fracturas, parálisis braquial, convulsiones si hay hemorragia intracraneal.', 'Trauma obstétrico', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Concepción Pérez Lara', '03:15:00', '34', '2.41', '36.16');
-- IDx Neonatal: 10010 : 20010
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 38, '98139333', 'Paula Moreno Roldán', '10/03/2024', '10/03/2024', '21:57:00', '25/03/2024', '04:04:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 87, Sector Simón Bolívar.' LIMIT 1), 'convulsiones, hipotonía, apnea, reflejos ausentes, encefalopatía.', 'Lesión cerebral hipóxica', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Alicia Uribe Palma', '21:57:00', '29', '3.23', '50.25');
-- IDx Neonatal: 10011 : 20011
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 37, '52712682', 'Pedro Burgos Valencia', '17/10/2024', '17/10/2024', '03:47:00', '12/11/2024', '16:22:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 77, Sector Simón Bolívar.' LIMIT 1), 'hipotonía, cardiopatías congénitas, retraso del desarrollo, infecciones frecuentes.', 'Síndrome de Down con complicaciones', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Adriana Zabala Ortiz', '03:47:00', '33', '2.68', '45.71');
-- IDx Neonatal: 10012 : 20012
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 36, '61589083', 'Matilde Peraza Cerrada', '20/11/2024', '20/11/2024', '02:26:00', '17/12/2024', '02:46:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 5, Sector Paraíso 1.' LIMIT 1), 'dificultad respiratoria, hemoptisis, cianosis, taquicardia, shock.', 'Hemorragia pulmonar', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Manuela Rojas Caraballo', '02:26:00', '42', '3.36', '43.66');
-- IDx Neonatal: 10013 : 20013
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 35, '21253297', 'Fernando Escobar Guerra', '02/08/2024', '02/08/2024', '07:39:00', '03/08/2024', '02:23:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 42, Sector Valmore Rodríguez.' LIMIT 1), 'microcefalia, hipertonía, convulsiones, retraso del desarrollo, calcificaciones intracraneales.', 'Infección por Zika congénito', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Mercedes Salas Montes', '07:39:00', '37', '3.26', '41.33');
-- IDx Neonatal: 10014 : 20014
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 34, '69465932', 'Rita Martínez Arévalo', '01/04/2024', '01/04/2024', '05:48:00', '16/04/2024', '15:49:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 61, Sector San José.' LIMIT 1), 'fiebre, taquipnea, quejido respiratorio, retracciones, cianosis.', 'Neumonía neonatal', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Alba Escobar Álvarez', '05:48:00', '35', '2.2', '45.51');
-- IDx Neonatal: 10015 : 20015
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 33, '75377072', 'Benjamín Téllez Cisneros', '31/01/2025', '31/01/2025', '02:18:00', '17/02/2025', '21:34:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 96, Sector Cementerio.' LIMIT 1), 'taquicardia, hepatomegalia, dificultad para alimentarse, cianosis.', 'Cardiomiopatía neonatal', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Susana Álvarez Cárdenas', '02:18:00', '22', '2.15', '40.49');
-- IDx Neonatal: 10016 : 20016
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 32, '40492196', 'Tomás Trujillo Benitez', '29/07/2025', '29/07/2025', '02:46:00', '02/08/2025', '23:03:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 18, Sector Colinas.' LIMIT 1), 'fiebre, taquipnea, quejido respiratorio, retracciones, cianosis.', 'Neumonía neonatal', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Elena Villalobos Sánchez', '02:46:00', '27', '2.07', '43.19');
-- IDx Neonatal: 10017 : 20017
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 31, '81572097', 'Agustín Naranjo Trujillo', '06/10/2024', '06/10/2024', '02:12:00', '19/10/2024', '15:37:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 25, Sector Colinas.' LIMIT 1), 'microcefalia, hipertonía, convulsiones, retraso del desarrollo, calcificaciones intracraneales.', 'Infección por Zika congénito', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Irma Benitez Quintero', '02:12:00', '22', '2.15', '40.96');
-- IDx Neonatal: 10018 : 20018
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 30, '58809880', 'Fernando Miranda Zambrano', '28/04/2024', '28/04/2024', '17:49:00', '07/05/2024', '15:26:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 68, Sector 19 de Marzo.' LIMIT 1), 'hipotensión, taquicardia, piel moteada, letargo, oliguria.', 'Shock séptico', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Matilde Roldán Sierra', '17:49:00', '40', '3.38', '41.45');
-- IDx Neonatal: 10019 : 20019
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 29, '90841153', 'Julio Carreño Arcila', '04/11/2025', '04/11/2025', '11:51:00', '06/11/2025', '18:48:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 17, Sector Simón Bolívar.' LIMIT 1), 'bradicardia o taquicardia, síncope, cianosis, letargo.', 'Arritmias congénitas', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Yulimar Quiñones Galindo', '11:51:00', '33', '2.92', '39.38');
-- IDx Neonatal: 10020 : 20020
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 28, '17984496', 'Natalia Báez Zapata', '04/08/2024', '04/08/2024', '02:43:00', '27/08/2024', '05:40:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 79, Sector Paraíso 1.' LIMIT 1), 'signos variables según el órgano afectado (cianosis, dificultad respiratoria, vómitos, abdomen distendido).', 'Malformaciones congénitas mayores', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Sofía López Cantillo', '02:43:00', '20', '2.64', '41.07');
-- IDx Neonatal: 10021 : 20021
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 27, '73778191', 'Andrés Blanco Cano', '04/04/2025', '04/04/2025', '17:50:00', '30/04/2025', '08:28:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 86, Sector Cementerio.' LIMIT 1), 'apnea, tono muscular bajo, convulsiones, acidosis, encefalopatía.', 'Hipoxia isquémica', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Juana Carvajal Paz', '17:50:00', '27', '2.31', '50.68');
-- IDx Neonatal: 10022 : 20022
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 26, '96315903', 'Elvira Silva Caraballo', '27/09/2024', '27/09/2024', '22:38:00', '23/10/2024', '05:22:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 48, Sector Pedro Camejo.' LIMIT 1), 'dificultad para respirar, succión débil, hipotermia, apnea, bajo peso, inmadurez pulmonar.', 'Prematuridad', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Margarita Sandoval Peña', '22:38:00', '23', '3.23', '38.77');
-- IDx Neonatal: 10023 : 20023
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 25, '81227695', 'Camila Marín Ortiz', '11/09/2024', '11/09/2024', '13:04:00', '21/09/2024', '00:15:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 79, Sector Campo Alegre.' LIMIT 1), 'signos variables según el órgano afectado (cianosis, dificultad respiratoria, vómitos, abdomen distendido).', 'Malformaciones congénitas mayores', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Rosa Calderón Méndez', '13:04:00', '42', '2.26', '38.87');
-- IDx Neonatal: 10024 : 20024
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 24, '55306412', 'Gabriel Colmenares Arteaga', '07/04/2024', '07/04/2024', '11:21:00', '13/04/2024', '01:23:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 6, Sector Pueblo Nuevo Sur.' LIMIT 1), 'piel fría, letargo, apnea, hipoglucemia, dificultad para alimentarse.', 'Hipotermia', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Luisa Rivas Caballero', '11:21:00', '22', '2.87', '38.62');
-- IDx Neonatal: 10025 : 20025
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 23, '42828304', 'Ninoska Zabala Quiroz', '25/04/2024', '25/04/2024', '02:58:00', '05/05/2024', '18:51:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 87, Sector Campo Oficina.' LIMIT 1), 'dificultad respiratoria, abdomen hundido, cianosis, sonidos respiratorios disminuidos.', 'Hernia diafragmática congénita', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Antonieta Valencia Moreno', '02:58:00', '29', '2.19', '36.08');
-- IDx Neonatal: 10026 : 20026
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 22, '17067320', 'Zulay Cano Consalvi', '19/12/2025', '19/12/2025', '02:07:00', '11/01/2026', '20:53:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 70, Sector Pueblo Nuevo Sur.' LIMIT 1), 'palpitaciones, taquicardia >220 lpm, palidez, dificultad para alimentarse.', 'Taquicardia supraventricular', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Milagros Miranda Jaimes', '02:07:00', '28', '3.4', '46.38');
-- IDx Neonatal: 10027 : 20027
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 21, '83106510', 'Ramiro Pinto Vera', '27/01/2024', '27/01/2024', '07:54:00', '19/02/2024', '04:40:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 73, Sector San José.' LIMIT 1), 'hipotermia, hipoglucemia, dificultad respiratoria no tratada.', 'Falta de atención neonatal inmediata', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Luisa Martínez Yánez', '07:54:00', '39', '3.46', '37.85');
-- IDx Neonatal: 10028 : 20028
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 20, '86304170', 'Baltazar Sánchez Moreno', '08/09/2024', '08/09/2024', '04:37:00', '16/09/2024', '06:23:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 75, Sector Casco Central.' LIMIT 1), 'dificultad respiratoria, hemoptisis, cianosis, taquicardia, shock.', 'Hemorragia pulmonar', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Mariana Zambrano Mejía', '04:37:00', '34', '2.1', '37.73');
-- IDx Neonatal: 10029 : 20029
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 19, '72533938', 'Samuel Colmenares Bravo', '20/08/2024', '20/08/2024', '23:05:00', '15/09/2024', '18:39:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 36, Sector San José.' LIMIT 1), 'dificultad respiratoria, hemoptisis, cianosis, taquicardia, shock.', 'Hemorragia pulmonar', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Pilar Calles Sierra', '23:05:00', '42', '2.23', '50.14');
-- IDx Neonatal: 10030 : 20030
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 18, '82906428', 'Sofía Quintero Fernández', '13/11/2024', '13/11/2024', '04:33:00', '19/11/2024', '18:42:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 33, Sector Campo Oficina.' LIMIT 1), 'hematomas, fracturas, parálisis braquial, convulsiones si hay hemorragia intracraneal.', 'Trauma obstétrico', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Lilian Henríquez Soto', '04:33:00', '41', '2.1', '48.02');
-- IDx Neonatal: 10031 : 20031
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 17, '48070377', 'Felipe Gómez Brito', '08/09/2025', '08/09/2025', '03:36:00', '15/09/2025', '05:32:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 39, Sector Central.' LIMIT 1), 'dificultad respiratoria progresiva, quejido espiratorio, retracciones, cianosis.', 'Enfermedad de membrana hialina', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Luisa Maldonado Gómez', '03:36:00', '34', '3.1', '51.76');
-- IDx Neonatal: 10032 : 20032
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 16, '57310722', 'Lilian Reyes Arévalo', '09/09/2024', '09/09/2024', '07:45:00', '13/09/2024', '15:48:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 69, Sector Casco Central.' LIMIT 1), 'hipotensión, taquicardia, piel moteada, letargo, oliguria.', 'Shock séptico', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Nora Peraza Cordero', '07:45:00', '28', '2.72', '43.34');
-- IDx Neonatal: 10033 : 20033
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 15, '80063368', 'Francisca Alvarado Cardona', '24/10/2024', '24/10/2024', '00:27:00', '29/10/2024', '22:49:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 80, Sector La Floresta.' LIMIT 1), 'distensión abdominal, sangre en heces, vómitos biliosos, letargo, fiebre.', 'Enterocolitis necrotizante', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Edith Villegas Cedeno', '00:27:00', '21', '3.24', '46.98');
-- IDx Neonatal: 10034 : 20034
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 14, '40861608', 'Camila Bermúdez Guerrero', '22/04/2024', '22/04/2024', '13:40:00', '19/05/2024', '21:05:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 61, Sector Las Villas.' LIMIT 1), 'hipotermia, hipoglucemia, dificultad para alimentarse, debilidad, ictericia.', 'Bajo peso al nacer', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Luisa Guerrero Gómez', '13:40:00', '31', '3.45', '36.7');
-- IDx Neonatal: 10035 : 20035
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 13, '97738636', 'Gabriel Torres Arguello', '04/10/2025', '04/10/2025', '06:52:00', '30/10/2025', '13:04:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 11, Sector Las Villas.' LIMIT 1), 'lesiones cutáneas, rinorrea sanguinolenta, hepatoesplenomegalia, ictericia, anemia.', 'Infección por sífilis congénita', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Esperanza Cardona Miranda', '06:52:00', '40', '2.2', '37.45');
-- IDx Neonatal: 10036 : 20036
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 12, '87951899', 'Gladys Barrios Aguilar', '04/07/2024', '04/07/2024', '18:34:00', '17/07/2024', '21:51:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 12, Sector Los Ángeles.' LIMIT 1), 'dificultad respiratoria, cianosis, taquipnea, quejido, retracciones.', 'Síndrome de aspiración meconial', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Teresa Olivo Maldonado', '18:34:00', '28', '2.85', '37.46');
-- IDx Neonatal: 10037 : 20037
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 11, '50599456', 'Alberto Bernal Téllez', '12/12/2025', '12/12/2025', '14:32:00', '02/01/2026', '23:12:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 94, Sector Campo Alegre.' LIMIT 1), 'hipotermia, hipoglucemia, dificultad respiratoria no tratada.', 'Falta de atención neonatal inmediata', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Paula Pulido Rivas', '14:32:00', '37', '3.15', '40.0');
-- IDx Neonatal: 10038 : 20038
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 10, '78533584', 'Rubén Barrios Marcano', '05/11/2024', '05/11/2024', '10:34:00', '20/11/2024', '05:42:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 36, Sector Campo Oficina.' LIMIT 1), 'hipoglucemia, pérdida de peso, ictericia, deshidratación.', 'Retraso en el inicio de la lactancia', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Edith Montes Castillo', '10:34:00', '42', '2.28', '48.75');
-- IDx Neonatal: 10039 : 20039
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 9, '40371043', 'Claudia Aguilar Gutiérrez', '02/02/2025', '02/02/2025', '02:41:00', '20/02/2025', '01:56:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 81, Sector Casco Central.' LIMIT 1), 'signos variables según el órgano afectado (cianosis, dificultad respiratoria, vómitos, abdomen distendido).', 'Malformaciones congénitas mayores', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Pilar Carvajal Pereira', '02:41:00', '23', '2.7', '40.19');
-- IDx Neonatal: 10040 : 20040
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 8, '46034600', 'Dolores Arjona Gil', '16/12/2024', '16/12/2024', '10:05:00', '26/12/2024', '12:14:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 41, Sector Pueblo Nuevo Sur.' LIMIT 1), 'hematomas, fracturas, parálisis braquial, convulsiones si hay hemorragia intracraneal.', 'Trauma obstétrico', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Noelia Valencia Arismendi', '10:05:00', '41', '2.36', '44.06');
-- IDx Neonatal: 10041 : 20041
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 7, '54673048', 'Jesús Cantillo Arroyo', '17/03/2024', '17/03/2024', '23:29:00', '08/04/2024', '00:06:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 68, Sector Paraíso 2.' LIMIT 1), 'fontanela abombada, macrocefalia, vómitos, irritabilidad, mirada en sol poniente.', 'Hidrocefalia', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Esther Zapata Valencia', '23:29:00', '37', '2.57', '48.38');
-- IDx Neonatal: 10042 : 20042
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 6, '42065898', 'Verónica Amaya Cordero', '30/11/2024', '30/11/2024', '04:47:00', '25/12/2024', '13:22:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 93, Sector Bicentenario.' LIMIT 1), 'dificultad respiratoria, abdomen hundido, cianosis, sonidos respiratorios disminuidos.', 'Hernia diafragmática congénita', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Pilar Márquez Valencia', '04:47:00', '25', '3.28', '46.6');
-- IDx Neonatal: 10043 : 20043
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 5, '15404128', 'Rosa Cano Suárez', '31/01/2025', '31/01/2025', '11:37:00', '27/02/2025', '16:23:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 57, Sector Casco Central.' LIMIT 1), 'cianosis, taquipnea, soplo cardíaco, dificultad respiratoria.', 'Hipertensión pulmonar persistente', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Andrea Varela Bolivar', '11:37:00', '30', '2.1', '44.72');
-- IDx Neonatal: 10044 : 20044
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 4, '20364152', 'Victoria Abreu Velásquez', '28/09/2025', '28/09/2025', '21:18:00', '19/10/2025', '02:38:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 33, Sector Campo Alegre.' LIMIT 1), 'sangrado umbilical persistente, hematomas, hemorragias internas, petequias.', 'Trastornos de la coagulación', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Manuela Zapata Peraza', '21:18:00', '38', '2.51', '51.46');
-- IDx Neonatal: 10045 : 20045
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 3, '95903509', 'Adriana Delgado Peraza', '12/02/2024', '12/02/2024', '17:24:00', '25/02/2024', '17:02:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 50, Sector Las Villas.' LIMIT 1), 'enrojecimiento, secreción purulenta, mal olor, fiebre, distensión abdominal.', 'Infección del cordón umbilical (onfalitis)', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Paula Casas Guevara', '17:24:00', '27', '3.09', '35.88');
-- IDx Neonatal: 10046 : 20046
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 2, '98733616', 'Jorge Bermúdez Baron', '15/02/2025', '15/02/2025', '01:34:00', '22/02/2025', '19:07:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 28, Sector La Floresta.' LIMIT 1), 'convulsiones, hipotonía, apnea, reflejos ausentes, encefalopatía.', 'Lesión cerebral hipóxica', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Ángela Salazar Santana', '01:34:00', '21', '2.95', '50.53');
-- IDx Neonatal: 10047 : 20047
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 1, '53032091', 'Gladys Borjas Peraza', '04/05/2024', '04/05/2024', '10:54:00', '15/05/2024', '13:16:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 83, Sector Paraíso 1.' LIMIT 1), 'ictericia, hepatomegalia, letargo, vómitos, fiebre.', 'Infección por hepatitis B', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Gabriela Cantillo Valdez', '10:54:00', '25', '3.07', '41.31');
-- IDx Neonatal: 10048 : 20048
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 0, '79187263', 'Emma Quiñones Fuentes', '22/12/2024', '22/12/2024', '19:49:00', '27/12/2024', '07:33:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 33, Sector Paraíso 1.' LIMIT 1), 'fiebre, irritabilidad, fontanela abombada, convulsiones, rechazo al alimento.', 'Meningitis neonatal', '2026-02-11');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Elisa Villalobos Gómez', '19:49:00', '21', '3.49', '49.26');
-- IDx Neonatal: 10049 : 20049
COMMIT;

-- TOTAL DE REGISTROS DE MORTALIDAD NEONATAL GENERADOS: 50
-- ADVERTENCIA: La forma en que se calcula el id_paciente 'MAX(id_paciente) - N' es una simplificación extrema. Asegúrate de que no haya otras inserciones en persona_paciente entre los pasos 1 y 3.
