BEGIN TRANSACTION;
-- --------------------------------------------------------------------------------------
-- SCRIPT 05: INSERCIÓN EN MORTALIDAD NEONATAL (3 Tablas en Cascada)
-- --------------------------------------------------------------------------------------

-- 1. INSERTAR ENTIDADES PACIENTE (Para obtener id_paciente, clave para mortalidad)
INSERT INTO persona_paciente (edad) VALUES ('18 Días');
INSERT INTO persona_paciente (edad) VALUES ('14 Días');
INSERT INTO persona_paciente (edad) VALUES ('28 Días');
INSERT INTO persona_paciente (edad) VALUES ('5 Días');
INSERT INTO persona_paciente (edad) VALUES ('6 Días');
INSERT INTO persona_paciente (edad) VALUES ('13 Días');
INSERT INTO persona_paciente (edad) VALUES ('12 Horas');
INSERT INTO persona_paciente (edad) VALUES ('22 Días');
INSERT INTO persona_paciente (edad) VALUES ('16 Días');
INSERT INTO persona_paciente (edad) VALUES ('15 Días');
INSERT INTO persona_paciente (edad) VALUES ('11 Días');
INSERT INTO persona_paciente (edad) VALUES ('27 Días');
INSERT INTO persona_paciente (edad) VALUES ('5 Días');
INSERT INTO persona_paciente (edad) VALUES ('8 Días');
INSERT INTO persona_paciente (edad) VALUES ('15 Días');
INSERT INTO persona_paciente (edad) VALUES ('13 Horas');
INSERT INTO persona_paciente (edad) VALUES ('19 Días');
INSERT INTO persona_paciente (edad) VALUES ('7 Días');
INSERT INTO persona_paciente (edad) VALUES ('10 Días');
INSERT INTO persona_paciente (edad) VALUES ('17 Días');
INSERT INTO persona_paciente (edad) VALUES ('8 Horas');
INSERT INTO persona_paciente (edad) VALUES ('20 Días');
INSERT INTO persona_paciente (edad) VALUES ('7 Días');
INSERT INTO persona_paciente (edad) VALUES ('22 Días');
INSERT INTO persona_paciente (edad) VALUES ('26 Días');
INSERT INTO persona_paciente (edad) VALUES ('17 Días');
INSERT INTO persona_paciente (edad) VALUES ('11 Días');
INSERT INTO persona_paciente (edad) VALUES ('9 Días');
INSERT INTO persona_paciente (edad) VALUES ('22 Días');
INSERT INTO persona_paciente (edad) VALUES ('10 Días');
INSERT INTO persona_paciente (edad) VALUES ('9 Días');
INSERT INTO persona_paciente (edad) VALUES ('1 Días');
INSERT INTO persona_paciente (edad) VALUES ('19 Días');
INSERT INTO persona_paciente (edad) VALUES ('19 Días');
INSERT INTO persona_paciente (edad) VALUES ('27 Días');
INSERT INTO persona_paciente (edad) VALUES ('16 Días');
INSERT INTO persona_paciente (edad) VALUES ('1 Días');
INSERT INTO persona_paciente (edad) VALUES ('17 Días');
INSERT INTO persona_paciente (edad) VALUES ('22 Días');
INSERT INTO persona_paciente (edad) VALUES ('12 Días');
INSERT INTO persona_paciente (edad) VALUES ('2 Días');
INSERT INTO persona_paciente (edad) VALUES ('3 Días');
INSERT INTO persona_paciente (edad) VALUES ('17 Días');
INSERT INTO persona_paciente (edad) VALUES ('21 Días');
INSERT INTO persona_paciente (edad) VALUES ('5 Días');
INSERT INTO persona_paciente (edad) VALUES ('17 Días');
INSERT INTO persona_paciente (edad) VALUES ('24 Días');
INSERT INTO persona_paciente (edad) VALUES ('10 Días');
INSERT INTO persona_paciente (edad) VALUES ('14 Días');
INSERT INTO persona_paciente (edad) VALUES ('20 Horas');

-- 2. INSERTAR ENTIDADES DIRECCIÓN (Para obtener id_direccion, clave para mortalidad)
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 49, Sector Valmore Rodríguez.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 98, Sector Casco Central.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 21, Sector Casco Central.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 80, Sector Central.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 42, Sector La Floresta.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 95, Sector Las Villas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 32, Sector La Floresta.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 85, Sector Paraíso 2.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 75, Sector Valmore Rodríguez.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 68, Sector Pueblo Nuevo Sur.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 93, Sector Los Ángeles.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 1, Sector Pedro Camejo.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 97, Sector Valmore Rodríguez.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 9, Sector Valmore Rodríguez.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 96, Sector La Floresta.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 29, Sector Campo Alegre.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 40, Sector Campo Alegre.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 32, Sector Casco Central.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 85, Sector Campo Alegre.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 51, Sector Los Ángeles.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 17, Sector Los Ángeles.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 61, Sector Casco Central.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 44, Sector Paraíso 1.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 31, Sector Pedro Camejo.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 23, Sector Los Ángeles.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 45, Sector Simón Bolívar.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 67, Sector Las Villas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 83, Sector Paraíso 1.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 10, Sector Las Villas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 75, Sector Los Ángeles.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 44, Sector Cementerio.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 88, Sector Pedro Camejo.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 74, Sector Las Villas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 96, Sector Las Villas.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 82, Sector Pueblo Nuevo Sur.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 47, Sector San José.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 41, Sector Valmore Rodríguez.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 88, Sector Valmore Rodríguez.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 52, Sector Paraíso 2.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 1, Sector Los Ángeles.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 23, Sector Pedro Camejo.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 2, Sector Barrio Blanco.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 58, Sector Campo Oficina.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 78, Sector La Floresta.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 44, Sector Los Ángeles.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 81, Sector Pedro Camejo.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 16, Sector Pueblo Nuevo Sur.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 5, Sector Los Ángeles.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 23, Sector Pueblo Nuevo Sur.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 89, Sector Pedro Camejo.', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));

-- 3. INSERTAR MORTALIDAD (Principal) y MORTALIDAD_NEONATAL (Detalle)
DELETE FROM mortalidad_neonatal;
DELETE FROM mortalidad;
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 49, '96484865', 'Valeria Rojas Blanco', '31/10/2024', '31/10/2024', '03:52:00', '18/11/2024', '20:53:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 49, Sector Valmore Rodríguez.' LIMIT 1), 'sangrado umbilical persistente, hematomas, hemorragias internas, petequias.', 'Trastornos de la coagulación', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Gladys Arévalo Valenzuela', '03:52:00', '21', '2.06', '51.46');
-- IDx Neonatal: 10000 : 20000
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 48, '45543779', 'Sofía Arrate Castillo', '06/11/2025', '06/11/2025', '18:04:00', '20/11/2025', '13:09:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 98, Sector Casco Central.' LIMIT 1), 'convulsiones, fontanela abombada, apnea, palidez, alteración del tono muscular.', 'Hemorragia intracraneal', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Yusbely Guerrero Suárez', '18:04:00', '33', '3.34', '37.54');
-- IDx Neonatal: 10001 : 20001
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 47, '12984807', 'Milagros Zambrano Cedeno', '10/03/2024', '10/03/2024', '22:35:00', '07/04/2024', '18:26:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 21, Sector Casco Central.' LIMIT 1), 'hipoglucemia, pérdida de peso, ictericia, deshidratación.', 'Retraso en el inicio de la lactancia', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Carmen Guerra Barrios', '22:35:00', '27', '3.45', '44.6');
-- IDx Neonatal: 10002 : 20002
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 46, '33404767', 'Eduardo Díaz Carrillo', '19/05/2024', '19/05/2024', '06:15:00', '24/05/2024', '07:56:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 80, Sector Central.' LIMIT 1), 'fiebre, taquipnea, quejido respiratorio, retracciones, cianosis.', 'Neumonía neonatal', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Nora Del Castillo Navia', '06:15:00', '27', '2.89', '50.21');
-- IDx Neonatal: 10003 : 20003
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 45, '83775974', 'René Borjas Carvajal', '08/04/2025', '08/04/2025', '05:56:00', '14/04/2025', '05:19:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 42, Sector La Floresta.' LIMIT 1), 'microcefalia, hipertonía, convulsiones, retraso del desarrollo, calcificaciones intracraneales.', 'Infección por Zika congénito', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Alba Morales Véliz', '05:56:00', '30', '2.4', '38.63');
-- IDx Neonatal: 10004 : 20004
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 44, '71273917', 'Fernanda Carvajal Pérez', '28/09/2024', '28/09/2024', '14:33:00', '11/10/2024', '20:47:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 95, Sector Las Villas.' LIMIT 1), 'fiebre, taquipnea, quejido respiratorio, retracciones, cianosis.', 'Neumonía neonatal', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Camila Roldán Izquierdo', '14:33:00', '20', '2.55', '42.69');
-- IDx Neonatal: 10005 : 20005
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 43, '59830964', 'Aarón Zambrano Arguello', '21/10/2024', '21/10/2024', '23:13:00', '21/10/2024', '23:44:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 32, Sector La Floresta.' LIMIT 1), 'piel fría, letargo, apnea, hipoglucemia, dificultad para alimentarse.', 'Hipotermia', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Ruth Yépez Castro', '23:13:00', '34', '2.64', '38.98');
-- IDx Neonatal: 10006 : 20006
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 42, '11950165', 'Zulay Mendoza Castro', '06/12/2024', '06/12/2024', '08:30:00', '28/12/2024', '09:46:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 85, Sector Paraíso 2.' LIMIT 1), 'hipotermia, hipoglucemia, dificultad respiratoria no tratada.', 'Falta de atención neonatal inmediata', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Carolina Peraza Véliz', '08:30:00', '30', '2.5', '35.24');
-- IDx Neonatal: 10007 : 20007
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 41, '69091876', 'Ignacio Sandoval López', '16/02/2024', '16/02/2024', '13:51:00', '03/03/2024', '03:25:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 75, Sector Valmore Rodríguez.' LIMIT 1), 'fontanela abombada, macrocefalia, vómitos, irritabilidad, mirada en sol poniente.', 'Hidrocefalia', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Juana Ramos Galindo', '13:51:00', '32', '3.49', '49.07');
-- IDx Neonatal: 10008 : 20008
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 40, '29129510', 'Mauricio Torres Gil', '05/08/2025', '05/08/2025', '22:24:00', '20/08/2025', '19:35:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 68, Sector Pueblo Nuevo Sur.' LIMIT 1), 'fiebre, taquipnea, quejido respiratorio, retracciones, cianosis.', 'Neumonía neonatal', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Rita Véliz Trujillo', '22:24:00', '27', '2.64', '40.44');
-- IDx Neonatal: 10009 : 20009
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 39, '61470940', 'Josefina Prieto Zabala', '21/04/2025', '21/04/2025', '06:31:00', '02/05/2025', '21:02:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 93, Sector Los Ángeles.' LIMIT 1), 'coloración amarilla de piel y ojos, somnolencia, succión débil, llanto agudo.', 'Ictericia severa', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Rosa María Paredes Barboza', '06:31:00', '29', '3.32', '46.59');
-- IDx Neonatal: 10010 : 20010
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 38, '73980323', 'Soledad Cardona Hernández', '28/09/2024', '28/09/2024', '05:47:00', '25/10/2024', '21:41:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 1, Sector Pedro Camejo.' LIMIT 1), 'masa en región lumbar, parálisis de miembros inferiores, hidrocefalia, incontinencia.', 'Espina bífida', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Verónica Benitez Marcano', '05:47:00', '41', '2.2', '47.45');
-- IDx Neonatal: 10011 : 20011
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 37, '99224935', 'Mateo Campos Fajardo', '07/06/2024', '07/06/2024', '13:34:00', '12/06/2024', '21:56:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 97, Sector Valmore Rodríguez.' LIMIT 1), 'dificultad respiratoria, hemoptisis, cianosis, taquicardia, shock.', 'Hemorragia pulmonar', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Matilde Herrera Zambrano', '13:34:00', '20', '3.39', '39.92');
-- IDx Neonatal: 10012 : 20012
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 36, '34275678', 'Manuel Romero Yánez', '28/09/2024', '28/09/2024', '17:45:00', '06/10/2024', '22:55:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 9, Sector Valmore Rodríguez.' LIMIT 1), 'hipoglucemia, pérdida de peso, ictericia, deshidratación.', 'Retraso en el inicio de la lactancia', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Adriana Cortez Romero', '17:45:00', '38', '3.44', '43.23');
-- IDx Neonatal: 10013 : 20013
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 35, '97755513', 'Ricardo Abreu Lucena', '09/04/2025', '09/04/2025', '23:15:00', '24/04/2025', '04:33:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 96, Sector La Floresta.' LIMIT 1), 'hipotermia, hipoglucemia, dificultad respiratoria no tratada.', 'Falta de atención neonatal inmediata', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Elena Cantillo Zambrano', '23:15:00', '36', '3.01', '50.37');
-- IDx Neonatal: 10014 : 20014
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 34, '57674863', 'Diego Bohorquez Olivo', '10/04/2025', '10/04/2025', '13:01:00', '10/04/2025', '01:22:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 29, Sector Campo Alegre.' LIMIT 1), 'cianosis, respiración irregular o ausente, tono muscular bajo, reflejos débiles, convulsiones.', 'Asfixia perinatal', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Paula Ramos Quiroz', '13:01:00', '33', '2.07', '48.63');
-- IDx Neonatal: 10015 : 20015
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 33, '92009686', 'Juan Caballero Hernández', '21/11/2025', '21/11/2025', '21:28:00', '10/12/2025', '09:52:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 40, Sector Campo Alegre.' LIMIT 1), 'signos variables según el órgano afectado (cianosis, dificultad respiratoria, vómitos, abdomen distendido).', 'Malformaciones congénitas mayores', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Diana Aguilar Rodríguez', '21:28:00', '26', '2.53', '36.31');
-- IDx Neonatal: 10016 : 20016
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 32, '88154590', 'Alicia Ibarra Santana', '22/02/2024', '22/02/2024', '06:57:00', '29/02/2024', '04:34:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 32, Sector Casco Central.' LIMIT 1), 'fiebre persistente, infecciones recurrentes, hepatoesplenomegalia, retraso del crecimiento.', 'Infección por VIH congénito', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Carmen Pinto Azocar', '06:57:00', '33', '2.71', '41.97');
-- IDx Neonatal: 10017 : 20017
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 31, '43060765', 'Bernardo Varela Celis', '05/10/2024', '05/10/2024', '17:01:00', '15/10/2024', '07:04:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 85, Sector Campo Alegre.' LIMIT 1), 'convulsiones, hipotonía, apnea, reflejos ausentes, encefalopatía.', 'Lesión cerebral hipóxica', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Emma Ospina Alvarado', '17:01:00', '38', '2.18', '39.05');
-- IDx Neonatal: 10018 : 20018
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 30, '58288874', 'Guillermo Valdez Asuaje', '02/03/2024', '02/03/2024', '18:36:00', '19/03/2024', '02:03:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 51, Sector Los Ángeles.' LIMIT 1), 'lesiones cutáneas, rinorrea sanguinolenta, hepatoesplenomegalia, ictericia, anemia.', 'Infección por sífilis congénita', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Adriana Correa Castro', '18:36:00', '42', '2.52', '50.84');
-- IDx Neonatal: 10019 : 20019
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 29, '99671933', 'Victoria Miranda Bernal', '26/07/2025', '26/07/2025', '02:45:00', '26/07/2025', '01:24:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 17, Sector Los Ángeles.' LIMIT 1), 'signos variables según el órgano afectado (cianosis, dificultad respiratoria, vómitos, abdomen distendido).', 'Malformaciones congénitas mayores', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Ángela Quintero Torres', '02:45:00', '38', '2.73', '43.6');
-- IDx Neonatal: 10020 : 20020
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 28, '92812095', 'Jacobo Molina Naranjo', '26/06/2025', '26/06/2025', '21:45:00', '16/07/2025', '04:39:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 61, Sector Casco Central.' LIMIT 1), 'bradicardia o taquicardia, síncope, cianosis, letargo.', 'Arritmias congénitas', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Rita Núñez Vidal', '21:45:00', '29', '3.18', '47.51');
-- IDx Neonatal: 10021 : 20021
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 27, '37647190', 'Simón Arguello Parra', '21/08/2025', '21/08/2025', '19:27:00', '28/08/2025', '02:15:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 44, Sector Paraíso 1.' LIMIT 1), 'cianosis, respiración irregular o ausente, tono muscular bajo, reflejos débiles, convulsiones.', 'Asfixia perinatal', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Raquel Jaimes Rodríguez', '19:27:00', '31', '2.49', '46.08');
-- IDx Neonatal: 10022 : 20022
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 26, '37428960', 'Guillermo Galindo Cruz', '30/01/2025', '30/01/2025', '03:34:00', '21/02/2025', '17:34:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 31, Sector Pedro Camejo.' LIMIT 1), 'cianosis, taquipnea, soplo cardíaco, dificultad respiratoria.', 'Hipertensión pulmonar persistente', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Manuela Betancourt Romero', '03:34:00', '42', '3.46', '35.98');
-- IDx Neonatal: 10023 : 20023
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 25, '81323930', 'Alicia García Bohorquez', '21/09/2024', '21/09/2024', '11:04:00', '17/10/2024', '09:26:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 23, Sector Los Ángeles.' LIMIT 1), 'masa en región lumbar, parálisis de miembros inferiores, hidrocefalia, incontinencia.', 'Espina bífida', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Cecilia Herrera Cedeno', '11:04:00', '35', '3.38', '44.18');
-- IDx Neonatal: 10024 : 20024
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 24, '67844036', 'Gladys Murillo Guerrero', '13/03/2024', '13/03/2024', '09:22:00', '30/03/2024', '16:37:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 45, Sector Simón Bolívar.' LIMIT 1), 'bradicardia o taquicardia, síncope, cianosis, letargo.', 'Arritmias congénitas', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Mercedes Paredes Caballero', '09:22:00', '27', '2.79', '40.36');
-- IDx Neonatal: 10025 : 20025
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 23, '59328921', 'Camila Guevara Henríquez', '16/10/2024', '16/10/2024', '08:08:00', '27/10/2024', '23:24:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 67, Sector Las Villas.' LIMIT 1), 'hipotensión, taquicardia, piel moteada, letargo, oliguria.', 'Shock séptico', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Susana Arguello Montes', '08:08:00', '21', '3.47', '44.73');
-- IDx Neonatal: 10026 : 20026
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 22, '90559644', 'Ramón Arias Cardona', '27/08/2024', '27/08/2024', '11:02:00', '05/09/2024', '03:53:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 83, Sector Paraíso 1.' LIMIT 1), 'temblores, irritabilidad, apnea, convulsiones, letargo.', 'Hipoglucemia neonatal', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Inés Del Castillo Salas', '11:02:00', '29', '2.58', '36.13');
-- IDx Neonatal: 10027 : 20027
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 21, '51146152', 'Concepción Salazar Ramírez', '14/01/2025', '14/01/2025', '23:34:00', '05/02/2025', '07:08:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 10, Sector Las Villas.' LIMIT 1), 'dificultad respiratoria, abdomen hundido, cianosis, sonidos respiratorios disminuidos.', 'Hernia diafragmática congénita', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Berta Asuaje Pereira', '23:34:00', '40', '3.05', '48.77');
-- IDx Neonatal: 10028 : 20028
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 20, '40066687', 'Baltazar Valenzuela Valera', '14/12/2025', '14/12/2025', '15:57:00', '24/12/2025', '11:52:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 75, Sector Los Ángeles.' LIMIT 1), 'evolución de patologías graves sin soporte vital.', 'Falta de acceso a cuidados intensivos neonatales', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Zulimar Carreño Navia', '15:57:00', '21', '2.08', '49.29');
-- IDx Neonatal: 10029 : 20029
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 19, '16277208', 'Alonso Marcano Ibarra', '01/10/2024', '01/10/2024', '10:13:00', '10/10/2024', '02:00:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 44, Sector Cementerio.' LIMIT 1), 'cianosis, taquipnea, soplo cardíaco, dificultad respiratoria.', 'Hipertensión pulmonar persistente', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Irma Salcedo Barros', '10:13:00', '24', '3.25', '47.78');
-- IDx Neonatal: 10030 : 20030
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 18, '35857375', 'Nelly Granados Cabrera', '03/08/2025', '03/08/2025', '00:30:00', '04/08/2025', '03:19:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 88, Sector Pedro Camejo.' LIMIT 1), 'asas intestinales expuestas al nacer, riesgo de sepsis, dificultad para alimentarse.', 'Gastrosquisis', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Emma Salazar Galindo', '00:30:00', '25', '2.64', '47.78');
-- IDx Neonatal: 10031 : 20031
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 17, '96403971', 'Gabriela Colina Galindo', '27/11/2024', '27/11/2024', '12:54:00', '16/12/2024', '15:46:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 74, Sector Las Villas.' LIMIT 1), 'cianosis, taquipnea, soplo cardíaco, dificultad respiratoria.', 'Hipertensión pulmonar persistente', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Ángela Vera Arismendi', '12:54:00', '24', '2.48', '46.4');
-- IDx Neonatal: 10032 : 20032
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 16, '37821640', 'Clara González Cardona', '12/12/2025', '12/12/2025', '11:25:00', '31/12/2025', '17:16:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 96, Sector Las Villas.' LIMIT 1), 'ausencia de bóveda craneana, exposición del tejido cerebral, letalidad inmediata.', 'Anencefalia', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Verónica Zambrano Redondo', '11:25:00', '28', '2.52', '40.21');
-- IDx Neonatal: 10033 : 20033
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 15, '84594514', 'Nora Bautista Castillo', '17/08/2025', '17/08/2025', '02:05:00', '13/09/2025', '05:30:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 82, Sector Pueblo Nuevo Sur.' LIMIT 1), 'fiebre, dificultad respiratoria, ictericia, convulsiones, sepsis.', 'Infección por Listeria', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Noelia Trejo Ramírez', '02:05:00', '21', '3.33', '50.34');
-- IDx Neonatal: 10034 : 20034
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 14, '56102548', 'Fernanda Caballero Naranjo', '14/02/2024', '14/02/2024', '05:56:00', '01/03/2024', '19:29:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 47, Sector San José.' LIMIT 1), 'hipoglucemia, deshidratación, pérdida de peso, letargo.', 'Alimentación inadecuada', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Mariángel Quiñones Caraballo', '05:56:00', '30', '2.19', '47.31');
-- IDx Neonatal: 10035 : 20035
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 13, '36849224', 'Verónica Bohorquez Duarte', '29/07/2024', '29/07/2024', '01:46:00', '30/07/2024', '22:27:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 41, Sector Valmore Rodríguez.' LIMIT 1), 'ictericia, hepatomegalia, letargo, vómitos, fiebre.', 'Infección por hepatitis B', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Esperanza Guerrero Marcano', '01:46:00', '26', '3.18', '42.93');
-- IDx Neonatal: 10036 : 20036
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 12, '34273500', 'Ignacio Serrano Salcedo', '26/10/2024', '26/10/2024', '10:31:00', '12/11/2024', '17:56:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 88, Sector Valmore Rodríguez.' LIMIT 1), 'signos variables según el órgano afectado (cianosis, dificultad respiratoria, vómitos, abdomen distendido).', 'Malformaciones congénitas mayores', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Isabel Fuentes Chávez', '10:31:00', '30', '2.33', '51.46');
-- IDx Neonatal: 10037 : 20037
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 11, '46838931', 'Leonardo Mejía Medina', '12/06/2025', '12/06/2025', '21:23:00', '04/07/2025', '17:27:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 52, Sector Paraíso 2.' LIMIT 1), 'hipoglucemia, deshidratación, pérdida de peso, letargo.', 'Alimentación inadecuada', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Alba Velásquez Vega', '21:23:00', '32', '3.21', '38.31');
-- IDx Neonatal: 10038 : 20038
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 10, '71155260', 'Olivia Villegas Prieto', '03/11/2024', '03/11/2024', '10:32:00', '15/11/2024', '10:15:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 1, Sector Los Ángeles.' LIMIT 1), 'fiebre persistente, infecciones recurrentes, hepatoesplenomegalia, retraso del crecimiento.', 'Infección por VIH congénito', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Yolanda Hernández Barreto', '10:32:00', '39', '2.99', '39.64');
-- IDx Neonatal: 10039 : 20039
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 9, '17049100', 'Teresa Galindo Fuentes', '29/07/2024', '29/07/2024', '08:18:00', '31/07/2024', '18:18:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 23, Sector Pedro Camejo.' LIMIT 1), 'apnea, tono muscular bajo, convulsiones, acidosis, encefalopatía.', 'Hipoxia isquémica', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Yusbely Téllez Marín', '08:18:00', '38', '2.56', '35.37');
-- IDx Neonatal: 10040 : 20040
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 8, '45765826', 'Gladys Olivo Henríquez', '08/10/2024', '08/10/2024', '21:56:00', '11/10/2024', '05:42:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 2, Sector Barrio Blanco.' LIMIT 1), 'palpitaciones, taquicardia >220 lpm, palidez, dificultad para alimentarse.', 'Taquicardia supraventricular', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Lucía Caballero Yépez', '21:56:00', '26', '2.53', '38.02');
-- IDx Neonatal: 10041 : 20041
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 7, '23406917', 'Alejandro Guerra Urdaneta', '04/05/2025', '04/05/2025', '16:03:00', '21/05/2025', '11:26:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 58, Sector Campo Oficina.' LIMIT 1), 'apnea, tono muscular bajo, convulsiones, acidosis, encefalopatía.', 'Hipoxia isquémica', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Clara Vásquez Navia', '16:03:00', '22', '2.33', '35.37');
-- IDx Neonatal: 10042 : 20042
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 6, '77317166', 'Alba Rosales Granados', '16/02/2025', '16/02/2025', '15:11:00', '09/03/2025', '20:00:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 78, Sector La Floresta.' LIMIT 1), 'sangrado umbilical persistente, hematomas, hemorragias internas, petequias.', 'Trastornos de la coagulación', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Olga Romero Quintana', '15:11:00', '31', '3.22', '46.59');
-- IDx Neonatal: 10043 : 20043
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 5, '19341556', 'Nelly Hernández Lara', '17/01/2025', '17/01/2025', '01:00:00', '22/01/2025', '07:44:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 44, Sector Los Ángeles.' LIMIT 1), 'apnea, tono muscular bajo, convulsiones, acidosis, encefalopatía.', 'Hipoxia isquémica', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Alba Villalobos Ortiz', '01:00:00', '38', '3.38', '37.14');
-- IDx Neonatal: 10044 : 20044
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 4, '22496736', 'Julian Chávez Padilla', '12/04/2024', '12/04/2024', '23:17:00', '29/04/2024', '08:51:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 81, Sector Pedro Camejo.' LIMIT 1), 'hematomas, fracturas, parálisis braquial, convulsiones si hay hemorragia intracraneal.', 'Trauma obstétrico', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Elvira Yépez Murillo', '23:17:00', '22', '2.92', '42.58');
-- IDx Neonatal: 10045 : 20045
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 3, '31992922', 'Wilmer Rivas Márquez', '20/07/2025', '20/07/2025', '05:24:00', '13/08/2025', '12:58:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 16, Sector Pueblo Nuevo Sur.' LIMIT 1), 'coloración amarilla de piel y ojos, somnolencia, succión débil, llanto agudo.', 'Ictericia severa', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Elisa Bohorquez Arrate', '05:24:00', '20', '2.89', '39.68');
-- IDx Neonatal: 10046 : 20046
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 2, '72467058', 'Elvira Izquierdo Arguello', '26/06/2025', '26/06/2025', '20:45:00', '06/07/2025', '00:39:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 5, Sector Los Ángeles.' LIMIT 1), 'ausencia de bóveda craneana, exposición del tejido cerebral, letalidad inmediata.', 'Anencefalia', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Emma Peña Suárez', '20:45:00', '41', '2.36', '41.27');
-- IDx Neonatal: 10047 : 20047
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 1, '82728720', 'Juan Borjas Navarro', '08/09/2025', '08/09/2025', '08:12:00', '22/09/2025', '01:52:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 23, Sector Pueblo Nuevo Sur.' LIMIT 1), 'hidrocefalia, convulsiones, coriorretinitis, ictericia, hepatoesplenomegalia.', 'Infección por toxoplasmosis', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Raquel Jiménez Cruz', '08:12:00', '24', '2.71', '44.16');
-- IDx Neonatal: 10048 : 20048
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 0, '95758430', 'Elvira Cedeno Celis', '20/02/2025', '20/02/2025', '02:45:00', '20/02/2025', '06:39:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 89, Sector Pedro Camejo.' LIMIT 1), 'fiebre, taquipnea, quejido respiratorio, retracciones, cianosis.', 'Neumonía neonatal', '2026-03-29');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Nelly Zapata Aguilar', '02:45:00', '29', '2.23', '49.46');
-- IDx Neonatal: 10049 : 20049
COMMIT;

-- TOTAL DE REGISTROS DE MORTALIDAD NEONATAL GENERADOS: 50
-- ADVERTENCIA: La forma en que se calcula el id_paciente 'MAX(id_paciente) - N' es una simplificación extrema. Asegúrate de que no haya otras inserciones en persona_paciente entre los pasos 1 y 3.
