BEGIN TRANSACTION;
-- --------------------------------------------------------------------------------------
-- SCRIPT 05: INSERCIÓN EN MORTALIDAD NEONATAL (3 Tablas en Cascada)
-- --------------------------------------------------------------------------------------

-- 1. INSERTAR ENTIDADES PACIENTE (Para obtener id_paciente, clave para mortalidad)
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);
INSERT INTO persona_paciente (edad) VALUES (0);

-- 2. INSERTAR ENTIDADES DIRECCIÓN (Para obtener id_direccion, clave para mortalidad)
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 2, Sector Vía Clarines, cerca del CDI. (Miranda)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 99, Sector Punta de Mata, cerca del CDI. (José Gregorio Monagas)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 10, Sector La Esperanza, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 44, Sector Punta de Mata, cerca del CDI. (José Gregorio Monagas)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 65, Sector Los Olivos, cerca del CDI. (Guanipa)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 82, Sector Barrio Simón Bolívar, cerca del CDI. (Guanipa)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 22, Sector La Esperanza, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 11, Sector Los Olivos, cerca del CDI. (Guanipa)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 80, Sector Centro, cerca del CDI. (Guanipa)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 66, Sector Km 55, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 4, Sector Vía Clarines, cerca del CDI. (Miranda)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 42, Sector Campo Alegre, cerca del CDI. (Simón Rodríguez)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 16, Sector La Esperanza, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 76, Sector La Esperanza, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Soledad'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 93, Sector Las Malvinas, cerca del CDI. (Miranda)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 78, Sector Campo Alegre, cerca del CDI. (Simón Rodríguez)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 74, Sector Pueblo Nuevo Sur, cerca del CDI. (Simón Rodríguez)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 62, Sector El Palomar, cerca del CDI. (Guanipa)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 90, Sector La Esperanza, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 18, Sector Barrio Simón Bolívar, cerca del CDI. (Guanipa)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 46, Sector Centro, cerca del CDI. (Guanipa)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 31, Sector Campo Alegre, cerca del CDI. (Simón Rodríguez)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 100, Sector El Centro, cerca del CDI. (José Gregorio Monagas)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 85, Sector Punta de Mata, cerca del CDI. (José Gregorio Monagas)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 43, Sector El Casco, cerca del CDI. (Miranda)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 70, Sector El Centro, cerca del CDI. (José Gregorio Monagas)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 25, Sector Barrio Simón Bolívar, cerca del CDI. (Guanipa)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Anaco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 1, Sector Pueblo Nuevo Sur, cerca del CDI. (Simón Rodríguez)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 87, Sector Punta de Mata, cerca del CDI. (José Gregorio Monagas)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Piar'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 35, Sector Km 55, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 22, Sector La Esperanza, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 94, Sector Sector Las Vegas, cerca del CDI. (José Gregorio Monagas)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Santa Cruz del Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 59, Sector El Casco, cerca del CDI. (Miranda)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 42, Sector Las Malvinas, cerca del CDI. (Miranda)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San Pablo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 100, Sector Pueblo Nuevo Sur, cerca del CDI. (Simón Rodríguez)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 1, Sector Km 55, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 4, Sector El Palomar, cerca del CDI. (Guanipa)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'El Chaparro'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 63, Sector Casco Central, cerca del CDI. (Simón Rodríguez)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 61, Sector Barrio Simón Bolívar, cerca del CDI. (Guanipa)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 84, Sector Las Malvinas, cerca del CDI. (Miranda)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Boca de Uchire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 56, Sector El Centro, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 28, Sector Los Olivos, cerca del CDI. (Guanipa)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'San José de Guanipa'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 89, Sector Km 55, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mamo'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 44, Sector Vía San Tomé, cerca del CDI. (Simón Rodríguez)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 95, Sector Casco Central, cerca del CDI. (Simón Rodríguez)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Atapirire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 59, Sector El Casco, cerca del CDI. (Miranda)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Clarines'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 54, Sector Punta de Mata, cerca del CDI. (José Gregorio Monagas)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Mapire'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Calle 82, Sector Campo Alegre, cerca del CDI. (Simón Rodríguez)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Edmundo Barrios'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Avenida 2, Sector Pueblo Nuevo Sur, cerca del CDI. (Simón Rodríguez)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Miguel Otero Silva'));
INSERT INTO direccion (descripcion, id_parroquia) VALUES ('Carrera 89, Sector La Esperanza, cerca del CDI. (Independencia)', (SELECT id_parroquia FROM parroquia WHERE nombre = 'Ciudad Orinoco'));

-- 3. INSERTAR MORTALIDAD (Principal) y MORTALIDAD_NEONATAL (Detalle)
DELETE FROM mortalidad_neonatal;
DELETE FROM mortalidad;
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 49, '41447683', 'Luis Redondo Henríquez', '23/02/2024', '23/02/2024', '02:56:00', '28/02/2024', '20:16:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 2, Sector Vía Clarines, cerca del CDI. (Miranda)' LIMIT 1), 'cianosis, taquipnea, soplo cardíaco, dificultad respiratoria.', 'Hipertensión pulmonar persistente', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Rosa Carvajal López', '02:56:00', '26', '2.72', '40.26');
-- IDx Neonatal: 10000 : 20000
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 48, '78595688', 'Gabriela Marques Yánez', '14/02/2024', '14/02/2024', '03:44:00', '15/02/2024', '15:33:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 99, Sector Punta de Mata, cerca del CDI. (José Gregorio Monagas)' LIMIT 1), 'apnea, tono muscular bajo, convulsiones, acidosis, encefalopatía.', 'Hipoxia isquémica', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Soledad Yánez Bandres', '03:44:00', '27', '2.33', '46.3');
-- IDx Neonatal: 10001 : 20001
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 47, '89285970', 'Lourdes Serrano Arcila', '10/10/2025', '10/10/2025', '14:38:00', '15/10/2025', '10:40:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 10, Sector La Esperanza, cerca del CDI. (Independencia)' LIMIT 1), 'fiebre, irritabilidad, fontanela abombada, convulsiones, rechazo al alimento.', 'Meningitis neonatal', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Victoria Rivera Valencia', '14:38:00', '26', '2.79', '47.57');
-- IDx Neonatal: 10002 : 20002
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 46, '92069953', 'Martín Rivera Zambrano', '24/06/2025', '24/06/2025', '01:29:00', '28/06/2025', '01:02:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 44, Sector Punta de Mata, cerca del CDI. (José Gregorio Monagas)' LIMIT 1), 'riesgo de asfixia, sepsis, hipotermia, hemorragia.', 'Nacimiento en domicilio sin asistencia', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Esperanza Salazar Briceño', '01:29:00', '28', '2.54', '36.29');
-- IDx Neonatal: 10003 : 20003
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 45, '79076525', 'Catalina Celis Escobar', '15/10/2024', '15/10/2024', '20:15:00', '10/11/2024', '09:59:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 65, Sector Los Olivos, cerca del CDI. (Guanipa)' LIMIT 1), 'piel fría, letargo, apnea, hipoglucemia, dificultad para alimentarse.', 'Hipotermia', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Luisana Cardona Azocar', '20:15:00', '37', '2.59', '42.73');
-- IDx Neonatal: 10004 : 20004
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 44, '29335491', 'Antonieta Cerrada Prieto', '05/12/2025', '05/12/2025', '01:30:00', '15/12/2025', '20:21:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 82, Sector Barrio Simón Bolívar, cerca del CDI. (Guanipa)' LIMIT 1), 'hidrocefalia, convulsiones, coriorretinitis, ictericia, hepatoesplenomegalia.', 'Infección por toxoplasmosis', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Lourdes Zambrano Méndez', '01:30:00', '32', '2.11', '49.53');
-- IDx Neonatal: 10005 : 20005
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 43, '13037285', 'Rodrigo Zambrano Contreras', '05/05/2025', '05/05/2025', '03:12:00', '22/05/2025', '08:52:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 22, Sector La Esperanza, cerca del CDI. (Independencia)' LIMIT 1), 'apnea, tono muscular bajo, convulsiones, acidosis, encefalopatía.', 'Hipoxia isquémica', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Catalina Naranjo Cano', '03:12:00', '33', '3.27', '38.66');
-- IDx Neonatal: 10006 : 20006
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 42, '90716029', 'Luis Téllez Cedeno', '12/02/2025', '12/02/2025', '22:12:00', '26/02/2025', '12:58:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 11, Sector Los Olivos, cerca del CDI. (Guanipa)' LIMIT 1), 'fiebre, dificultad respiratoria, ictericia, convulsiones, sepsis.', 'Infección por Listeria', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Patricia Redondo Gallegos', '22:12:00', '23', '3.49', '42.8');
-- IDx Neonatal: 10007 : 20007
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 41, '53992469', 'Consuelo Galindo Paredes', '06/04/2024', '06/04/2024', '12:35:00', '24/04/2024', '15:28:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 80, Sector Centro, cerca del CDI. (Guanipa)' LIMIT 1), 'hidrocefalia, convulsiones, coriorretinitis, ictericia, hepatoesplenomegalia.', 'Infección por toxoplasmosis', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Paula Téllez González', '12:35:00', '37', '2.53', '44.9');
-- IDx Neonatal: 10008 : 20008
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 40, '72494670', 'Daniel Peraza Velásquez', '29/05/2025', '29/05/2025', '01:03:00', '21/06/2025', '16:36:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 66, Sector Km 55, cerca del CDI. (Independencia)' LIMIT 1), 'cianosis, taquipnea, soplo cardíaco, dificultad respiratoria.', 'Hipertensión pulmonar persistente', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Miriam Benitez Palacios', '01:03:00', '23', '2.97', '40.78');
-- IDx Neonatal: 10009 : 20009
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 39, '41427517', 'Pilar Borjas García', '01/07/2025', '01/07/2025', '09:15:00', '26/07/2025', '16:18:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 4, Sector Vía Clarines, cerca del CDI. (Miranda)' LIMIT 1), 'bradicardia o taquicardia, síncope, cianosis, letargo.', 'Arritmias congénitas', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Silvia Ospina Salcedo', '09:15:00', '35', '3.1', '40.65');
-- IDx Neonatal: 10010 : 20010
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 38, '38815374', 'Bernardo Ramos Briceño', '19/12/2024', '19/12/2024', '02:25:00', '07/01/2025', '23:48:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 42, Sector Campo Alegre, cerca del CDI. (Simón Rodríguez)' LIMIT 1), 'salivación excesiva, tos al alimentarse, dificultad para tragar, distensión abdominal.', 'Atresia esofágica', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Esther Peraza González', '02:25:00', '31', '2.36', '37.84');
-- IDx Neonatal: 10011 : 20011
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 37, '64125366', 'Lorenzo Briceño Cruz', '05/12/2025', '05/12/2025', '04:48:00', '24/12/2025', '17:15:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 16, Sector La Esperanza, cerca del CDI. (Independencia)' LIMIT 1), 'vómitos, letargo, hipoglucemia, convulsiones, olor corporal inusual.', 'Trastornos metabólicos congénitos', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Beatriz Escobar Ramos', '04:48:00', '42', '2.76', '42.45');
-- IDx Neonatal: 10012 : 20012
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 36, '87831521', 'Miguel Varela Zambrano', '23/11/2025', '23/11/2025', '20:15:00', '19/12/2025', '15:13:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 76, Sector La Esperanza, cerca del CDI. (Independencia)' LIMIT 1), 'cianosis, soplo cardíaco, taquipnea, sudoración al alimentarse, fatiga.', 'Cardiopatías congénitas', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Rocío Maldonado Méndez', '20:15:00', '25', '2.9', '48.46');
-- IDx Neonatal: 10013 : 20013
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 35, '76837938', 'Emilio Murillo Marín', '12/07/2025', '12/07/2025', '08:09:00', '25/07/2025', '20:49:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 93, Sector Las Malvinas, cerca del CDI. (Miranda)' LIMIT 1), 'fiebre, taquipnea, quejido respiratorio, retracciones, cianosis.', 'Neumonía neonatal', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Carmen Paz Galindo', '08:09:00', '25', '2.19', '40.17');
-- IDx Neonatal: 10014 : 20014
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 34, '75890595', 'Isabel Marques Vera', '10/08/2024', '10/08/2024', '03:44:00', '05/09/2024', '03:55:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 78, Sector Campo Alegre, cerca del CDI. (Simón Rodríguez)' LIMIT 1), 'distensión abdominal, sangre en heces, vómitos biliosos, letargo, fiebre.', 'Enterocolitis necrotizante', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Lismar Pérez Peña', '03:44:00', '36', '2.43', '36.77');
-- IDx Neonatal: 10015 : 20015
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 33, '76875734', 'Lismar Izquierdo Miranda', '21/12/2024', '21/12/2024', '05:53:00', '16/01/2025', '23:34:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 74, Sector Pueblo Nuevo Sur, cerca del CDI. (Simón Rodríguez)' LIMIT 1), 'palpitaciones, taquicardia >220 lpm, palidez, dificultad para alimentarse.', 'Taquicardia supraventricular', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Isabel Henríquez Figueroa', '05:53:00', '33', '3.45', '44.35');
-- IDx Neonatal: 10016 : 20016
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 32, '63710182', 'Luis Abreu Cruz', '17/05/2025', '17/05/2025', '10:18:00', '23/05/2025', '19:23:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 62, Sector El Palomar, cerca del CDI. (Guanipa)' LIMIT 1), 'fiebre o hipotermia, letargo, rechazo al alimento, dificultad respiratoria, ictericia.', 'Sepsis neonatal', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Rosa María Salinas Santana', '10:18:00', '36', '2.62', '35.04');
-- IDx Neonatal: 10017 : 20017
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 31, '68556062', 'Julia Núñez Consalvi', '09/05/2024', '09/05/2024', '13:55:00', '11/05/2024', '05:38:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 90, Sector La Esperanza, cerca del CDI. (Independencia)' LIMIT 1), 'microcefalia, hipertonía, convulsiones, retraso del desarrollo, calcificaciones intracraneales.', 'Infección por Zika congénito', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Lilian Calderón Gutiérrez', '13:55:00', '41', '3.22', '47.57');
-- IDx Neonatal: 10018 : 20018
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 30, '91565630', 'Victoria Suárez Rivera', '22/02/2025', '22/02/2025', '14:48:00', '13/03/2025', '07:44:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 18, Sector Barrio Simón Bolívar, cerca del CDI. (Guanipa)' LIMIT 1), 'hipotermia, hipoglucemia, dificultad respiratoria no tratada.', 'Falta de atención neonatal inmediata', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Inés Palma Cedeno', '14:48:00', '40', '3.07', '40.7');
-- IDx Neonatal: 10019 : 20019
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 29, '88662278', 'Eduardo Pereira Navia', '16/03/2025', '16/03/2025', '21:29:00', '08/04/2025', '04:47:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 46, Sector Centro, cerca del CDI. (Guanipa)' LIMIT 1), 'sangrado umbilical persistente, hematomas, hemorragias internas, petequias.', 'Trastornos de la coagulación', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Matilde Salas Véliz', '21:29:00', '41', '2.4', '50.61');
-- IDx Neonatal: 10020 : 20020
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 28, '12249729', 'Zulay Ruiz Jaimes', '14/08/2024', '14/08/2024', '03:12:00', '01/09/2024', '21:26:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 31, Sector Campo Alegre, cerca del CDI. (Simón Rodríguez)' LIMIT 1), 'lesiones cutáneas, rinorrea sanguinolenta, hepatoesplenomegalia, ictericia, anemia.', 'Infección por sífilis congénita', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Valentina Vega Padilla', '03:12:00', '25', '3.36', '46.88');
-- IDx Neonatal: 10021 : 20021
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 27, '56656270', 'Jesús Alvarado Vega', '19/12/2024', '19/12/2024', '19:44:00', '06/01/2025', '06:08:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 100, Sector El Centro, cerca del CDI. (José Gregorio Monagas)' LIMIT 1), 'enrojecimiento, secreción purulenta, mal olor, fiebre, distensión abdominal.', 'Infección del cordón umbilical (onfalitis)', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Olga Hernández Cardona', '19:44:00', '22', '2.71', '35.99');
-- IDx Neonatal: 10022 : 20022
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 26, '32981767', 'Susana Zambrano Herrera', '24/02/2024', '24/02/2024', '14:37:00', '22/03/2024', '04:26:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 85, Sector Punta de Mata, cerca del CDI. (José Gregorio Monagas)' LIMIT 1), 'lesiones cutáneas, rinorrea sanguinolenta, hepatoesplenomegalia, ictericia, anemia.', 'Infección por sífilis congénita', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Paula Sánchez Mendoza', '14:37:00', '29', '2.82', '51.38');
-- IDx Neonatal: 10023 : 20023
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 25, '57094298', 'Josefina Gallegos Caraballo', '22/08/2025', '22/08/2025', '20:44:00', '19/09/2025', '23:12:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 43, Sector El Casco, cerca del CDI. (Miranda)' LIMIT 1), 'dificultad respiratoria progresiva, quejido espiratorio, retracciones, cianosis.', 'Enfermedad de membrana hialina', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Elena Avila Ramos', '20:44:00', '34', '2.12', '37.88');
-- IDx Neonatal: 10024 : 20024
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 24, '59154826', 'Luisana Torres Vidal', '12/07/2025', '12/07/2025', '03:24:00', '04/08/2025', '13:44:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 70, Sector El Centro, cerca del CDI. (José Gregorio Monagas)' LIMIT 1), 'dificultad para respirar, succión débil, hipotermia, apnea, bajo peso, inmadurez pulmonar.', 'Prematuridad', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Gabriela Navia Castañeda', '03:24:00', '23', '2.36', '39.33');
-- IDx Neonatal: 10025 : 20025
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 23, '39544087', 'Martín Alvarado Azocar', '22/07/2024', '22/07/2024', '20:02:00', '06/08/2024', '14:33:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 25, Sector Barrio Simón Bolívar, cerca del CDI. (Guanipa)' LIMIT 1), 'hipoglucemia, deshidratación, pérdida de peso, letargo.', 'Alimentación inadecuada', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Olga Contreras Ramos', '20:02:00', '28', '2.79', '43.46');
-- IDx Neonatal: 10026 : 20026
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 22, '52100511', 'Gladys Blanco Cárdenas', '28/12/2025', '28/12/2025', '19:36:00', '10/01/2026', '03:29:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 1, Sector Pueblo Nuevo Sur, cerca del CDI. (Simón Rodríguez)' LIMIT 1), 'cianosis, respiración irregular o ausente, tono muscular bajo, reflejos débiles, convulsiones.', 'Asfixia perinatal', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Eva Zambrano Urdaneta', '19:36:00', '28', '3.15', '41.5');
-- IDx Neonatal: 10027 : 20027
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 21, '43164526', 'Raúl Cardona Torres', '21/04/2024', '21/04/2024', '18:12:00', '07/05/2024', '22:57:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 87, Sector Punta de Mata, cerca del CDI. (José Gregorio Monagas)' LIMIT 1), 'hipoglucemia, deshidratación, pérdida de peso, letargo.', 'Alimentación inadecuada', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Zulimar Téllez Delgado', '18:12:00', '40', '2.53', '42.11');
-- IDx Neonatal: 10028 : 20028
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 20, '26339177', 'Cristian Pinto Rivas', '25/12/2024', '25/12/2024', '04:13:00', '10/01/2025', '01:11:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 35, Sector Km 55, cerca del CDI. (Independencia)' LIMIT 1), 'palpitaciones, taquicardia >220 lpm, palidez, dificultad para alimentarse.', 'Taquicardia supraventricular', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Francisca Cárdenas Borjas', '04:13:00', '25', '3.06', '46.12');
-- IDx Neonatal: 10029 : 20029
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 19, '56255979', 'Fermín Zabala Izquierdo', '28/04/2025', '28/04/2025', '10:09:00', '17/05/2025', '14:12:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 22, Sector La Esperanza, cerca del CDI. (Independencia)' LIMIT 1), 'distensión abdominal, sangre en heces, vómitos biliosos, letargo, fiebre.', 'Enterocolitis necrotizante', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Yusmary Consalvi Zambrano', '10:09:00', '32', '2.42', '47.48');
-- IDx Neonatal: 10030 : 20030
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 18, '94227976', 'Fidel Salinas Chávez', '19/01/2025', '19/01/2025', '07:27:00', '29/01/2025', '17:16:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 94, Sector Sector Las Vegas, cerca del CDI. (José Gregorio Monagas)' LIMIT 1), 'temblores, irritabilidad, apnea, convulsiones, letargo.', 'Hipoglucemia neonatal', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Ángela Henríquez Reyes', '07:27:00', '39', '3.19', '49.61');
-- IDx Neonatal: 10031 : 20031
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 17, '71333924', 'Adrián Urdaneta Uribe', '06/05/2025', '06/05/2025', '02:24:00', '30/05/2025', '01:47:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 59, Sector El Casco, cerca del CDI. (Miranda)' LIMIT 1), 'coloración amarilla de piel y ojos, somnolencia, succión débil, llanto agudo.', 'Ictericia severa', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Lucía Ortega Ortega', '02:24:00', '20', '2.57', '47.21');
-- IDx Neonatal: 10032 : 20032
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 16, '76502268', 'Rafael Molina Rojas', '07/06/2025', '07/06/2025', '05:31:00', '22/06/2025', '19:56:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 42, Sector Las Malvinas, cerca del CDI. (Miranda)' LIMIT 1), 'cianosis, taquipnea, soplo cardíaco, dificultad respiratoria.', 'Hipertensión pulmonar persistente', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Mariángel Arévalo Álvarez', '05:31:00', '41', '3.11', '45.07');
-- IDx Neonatal: 10033 : 20033
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 15, '83664376', 'Benjamín Colmenares Ruiz', '01/12/2025', '01/12/2025', '16:37:00', '07/12/2025', '09:53:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 100, Sector Pueblo Nuevo Sur, cerca del CDI. (Simón Rodríguez)' LIMIT 1), 'bradicardia o taquicardia, síncope, cianosis, letargo.', 'Arritmias congénitas', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Natalia Duarte Ramos', '16:37:00', '39', '3.33', '46.7');
-- IDx Neonatal: 10034 : 20034
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 14, '85675164', 'Jimena González Arguello', '18/01/2025', '18/01/2025', '10:15:00', '23/01/2025', '06:01:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 1, Sector Km 55, cerca del CDI. (Independencia)' LIMIT 1), 'evolución de patologías graves sin soporte vital.', 'Falta de acceso a cuidados intensivos neonatales', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Nora Cadenas Arias', '10:15:00', '42', '3.49', '39.61');
-- IDx Neonatal: 10035 : 20035
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 13, '56519855', 'Guillermo Yépez Gil', '11/03/2025', '11/03/2025', '08:13:00', '03/04/2025', '18:36:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 4, Sector El Palomar, cerca del CDI. (Guanipa)' LIMIT 1), 'microcefalia, hipertonía, convulsiones, retraso del desarrollo, calcificaciones intracraneales.', 'Infección por Zika congénito', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Amparo Navarro Guevara', '08:13:00', '26', '3.36', '44.76');
-- IDx Neonatal: 10036 : 20036
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 12, '85458139', 'Eugenio Burgos Valencia', '20/07/2024', '20/07/2024', '16:13:00', '10/08/2024', '11:13:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 63, Sector Casco Central, cerca del CDI. (Simón Rodríguez)' LIMIT 1), 'signos variables según el órgano afectado (cianosis, dificultad respiratoria, vómitos, abdomen distendido).', 'Malformaciones congénitas mayores', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Susana Briceño Aular', '16:13:00', '32', '2.88', '46.83');
-- IDx Neonatal: 10037 : 20037
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 11, '40742224', 'Rodrigo Marcano Varela', '03/06/2024', '03/06/2024', '03:34:00', '05/06/2024', '00:21:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 61, Sector Barrio Simón Bolívar, cerca del CDI. (Guanipa)' LIMIT 1), 'vómitos, letargo, hipoglucemia, convulsiones, olor corporal inusual.', 'Trastornos metabólicos congénitos', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Nelly Quintana García', '03:34:00', '36', '2.73', '40.12');
-- IDx Neonatal: 10038 : 20038
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 10, '72104164', 'Susana Lara Mora', '03/04/2025', '03/04/2025', '15:53:00', '03/04/2025', '23:51:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 84, Sector Las Malvinas, cerca del CDI. (Miranda)' LIMIT 1), 'fiebre, dificultad respiratoria, ictericia, convulsiones, sepsis.', 'Infección por Listeria', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Adriana Zapata Lucena', '15:53:00', '37', '3.16', '48.97');
-- IDx Neonatal: 10039 : 20039
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 9, '55442118', 'Francisco Bello Villalobos', '19/03/2024', '19/03/2024', '02:56:00', '09/04/2024', '05:15:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 56, Sector El Centro, cerca del CDI. (Independencia)' LIMIT 1), 'dificultad respiratoria, hemoptisis, cianosis, taquicardia, shock.', 'Hemorragia pulmonar', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Lucía Romero Del Castillo', '02:56:00', '42', '3.26', '48.76');
-- IDx Neonatal: 10040 : 20040
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 8, '36149057', 'Julio Murillo Caballero', '19/10/2024', '19/10/2024', '18:43:00', '22/10/2024', '11:05:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 28, Sector Los Olivos, cerca del CDI. (Guanipa)' LIMIT 1), 'ictericia, hepatomegalia, letargo, vómitos, fiebre.', 'Infección por hepatitis B', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Adriana Ibarra Murillo', '18:43:00', '37', '2.82', '38.54');
-- IDx Neonatal: 10041 : 20041
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 7, '97923303', 'Clara Ortega Redondo', '09/05/2024', '09/05/2024', '00:35:00', '12/05/2024', '06:08:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 89, Sector Km 55, cerca del CDI. (Independencia)' LIMIT 1), 'cataratas, sordera, cardiopatías, púrpura, retraso del crecimiento.', 'Infección por rubéola congénita', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Luisa León Varela', '00:35:00', '31', '2.62', '36.36');
-- IDx Neonatal: 10042 : 20042
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 6, '89030787', 'Esteban Cruz Salazar', '28/03/2024', '28/03/2024', '16:32:00', '23/04/2024', '23:12:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 44, Sector Vía San Tomé, cerca del CDI. (Simón Rodríguez)' LIMIT 1), 'dificultad respiratoria, cianosis, taquipnea, quejido, retracciones.', 'Síndrome de aspiración meconial', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Margarita Flores Arias', '16:32:00', '31', '2.05', '35.79');
-- IDx Neonatal: 10043 : 20043
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 5, '92056646', 'Rosa Varela Montes', '22/04/2025', '22/04/2025', '07:54:00', '24/04/2025', '04:29:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 95, Sector Casco Central, cerca del CDI. (Simón Rodríguez)' LIMIT 1), 'bradicardia o taquicardia, síncope, cianosis, letargo.', 'Arritmias congénitas', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Beatriz Baron Estrada', '07:54:00', '20', '3.45', '50.81');
-- IDx Neonatal: 10044 : 20044
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 4, '71307404', 'Carolina Díaz Ramos', '25/10/2025', '25/10/2025', '11:25:00', '03/11/2025', '04:17:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 59, Sector El Casco, cerca del CDI. (Miranda)' LIMIT 1), 'dificultad para respirar, succión débil, hipotermia, apnea, bajo peso, inmadurez pulmonar.', 'Prematuridad', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Catalina Lucena Fuentes', '11:25:00', '31', '3.29', '51.39');
-- IDx Neonatal: 10045 : 20045
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 3, '59419240', 'Gabriela Brito Bustamante', '20/03/2024', '20/03/2024', '22:05:00', '06/04/2024', '15:21:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 54, Sector Punta de Mata, cerca del CDI. (José Gregorio Monagas)' LIMIT 1), 'hipotensión, taquicardia, piel moteada, letargo, oliguria.', 'Shock séptico', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Mariángel Arias Yépez', '22:05:00', '40', '3.15', '37.16');
-- IDx Neonatal: 10046 : 20046
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 2, '73473259', 'Felipe Moreno Casas', '04/03/2025', '04/03/2025', '11:30:00', '21/03/2025', '10:12:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Calle 82, Sector Campo Alegre, cerca del CDI. (Simón Rodríguez)' LIMIT 1), 'signos variables según el órgano afectado (cianosis, dificultad respiratoria, vómitos, abdomen distendido).', 'Malformaciones congénitas mayores', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Yolanda Benitez Zabala', '11:30:00', '36', '3.42', '49.06');
-- IDx Neonatal: 10047 : 20047
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 1, '70040753', 'Alicia Ibarra Zambrano', '12/12/2025', '12/12/2025', '01:13:00', '09/01/2026', '14:01:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Avenida 2, Sector Pueblo Nuevo Sur, cerca del CDI. (Simón Rodríguez)' LIMIT 1), 'ictericia, hepatomegalia, letargo, vómitos, fiebre.', 'Infección por hepatitis B', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Carolina Correa Olivo', '01:13:00', '38', '2.47', '45.89');
-- IDx Neonatal: 10048 : 20048
INSERT INTO mortalidad (id_paciente, historia_clinica, nombres_apellidos, fecha_nacimiento, fecha_ingreso, hora_ingreso, fecha_defuncion, hora_defuncion, id_direccion, idx_ingreso, idx_defuncion, fecha_registro_formulario) VALUES ((SELECT MAX(id_paciente) FROM persona_paciente) - 0, '23515085', 'Luisana Cantillo Medina', '05/05/2024', '05/05/2024', '05:00:00', '27/05/2024', '17:13:00', (SELECT id_direccion FROM direccion WHERE descripcion = 'Carrera 89, Sector La Esperanza, cerca del CDI. (Independencia)' LIMIT 1), 'dificultad respiratoria, hemoptisis, cianosis, taquicardia, shock.', 'Hemorragia pulmonar', '2025-12-15');
INSERT INTO mortalidad_neonatal (id_m, nombre_madre, hora_nacimiento, semanas_gestacion, peso, talla) VALUES (LAST_INSERT_ROWID(), 'Luisa Figueroa Maldonado', '05:00:00', '31', '3.02', '35.76');
-- IDx Neonatal: 10049 : 20049
COMMIT;

-- TOTAL DE REGISTROS DE MORTALIDAD NEONATAL GENERADOS: 50
-- ADVERTENCIA: La forma en que se calcula el id_paciente 'MAX(id_paciente) - N' es una simplificación extrema. Asegúrate de que no haya otras inserciones en persona_paciente entre los pasos 1 y 3.
