causas_sintomas_morta_neonatal = {
    "Prematuridad": "dificultad para respirar, succión débil, hipotermia, apnea, bajo peso, inmadurez pulmonar.",
    "Bajo peso al nacer": "hipotermia, hipoglucemia, dificultad para alimentarse, debilidad, ictericia.",
    "Asfixia perinatal": "cianosis, respiración irregular o ausente, tono muscular bajo, reflejos débiles, convulsiones.",
    "Sepsis neonatal": "fiebre o hipotermia, letargo, rechazo al alimento, dificultad respiratoria, ictericia.",
    "Infección del cordón umbilical (onfalitis)": "enrojecimiento, secreción purulenta, mal olor, fiebre, distensión abdominal.",
    "Neumonía neonatal": "fiebre, taquipnea, quejido respiratorio, retracciones, cianosis.",
    "Meningitis neonatal": "fiebre, irritabilidad, fontanela abombada, convulsiones, rechazo al alimento.",
    "Malformaciones congénitas mayores": "signos variables según el órgano afectado (cianosis, dificultad respiratoria, vómitos, abdomen distendido).",
    "Cardiopatías congénitas": "cianosis, soplo cardíaco, taquipnea, sudoración al alimentarse, fatiga.",
    "Enfermedad de membrana hialina": "dificultad respiratoria progresiva, quejido espiratorio, retracciones, cianosis.",
    "Hipoglucemia neonatal": "temblores, irritabilidad, apnea, convulsiones, letargo.",
    "Hipotermia": "piel fría, letargo, apnea, hipoglucemia, dificultad para alimentarse.",
    "Ictericia severa": "coloración amarilla de piel y ojos, somnolencia, succión débil, llanto agudo.",
    "Hemorragia intracraneal": "convulsiones, fontanela abombada, apnea, palidez, alteración del tono muscular.",
    "Síndrome de aspiración meconial": "dificultad respiratoria, cianosis, taquipnea, quejido, retracciones.",
    "Enterocolitis necrotizante": "distensión abdominal, sangre en heces, vómitos biliosos, letargo, fiebre.",
    "Infección por estreptococo del grupo B": "fiebre, dificultad respiratoria, letargo, convulsiones, shock.",
    "Infección por Listeria": "fiebre, dificultad respiratoria, ictericia, convulsiones, sepsis.",
    "Infección por citomegalovirus": "ictericia, hepatoesplenomegalia, microcefalia, convulsiones, petequias.",
    "Infección por toxoplasmosis": "hidrocefalia, convulsiones, coriorretinitis, ictericia, hepatoesplenomegalia.",
    "Infección por herpes neonatal": "lesiones vesiculares, fiebre, letargo, convulsiones, hepatitis.",
    "Infección por VIH congénito": "fiebre persistente, infecciones recurrentes, hepatoesplenomegalia, retraso del crecimiento.",
    "Infección por sífilis congénita": "lesiones cutáneas, rinorrea sanguinolenta, hepatoesplenomegalia, ictericia, anemia.",
    "Infección por rubéola congénita": "cataratas, sordera, cardiopatías, púrpura, retraso del crecimiento.",
    "Infección por Zika congénito": "microcefalia, hipertonía, convulsiones, retraso del desarrollo, calcificaciones intracraneales.",
    "Infección por hepatitis B": "ictericia, hepatomegalia, letargo, vómitos, fiebre.",
    "Hipoxia isquémica": "apnea, tono muscular bajo, convulsiones, acidosis, encefalopatía.",
    "Trastornos metabólicos congénitos": "vómitos, letargo, hipoglucemia, convulsiones, olor corporal inusual.",
    "Atresia esofágica": "salivación excesiva, tos al alimentarse, dificultad para tragar, distensión abdominal.",
    "Hernia diafragmática congénita": "dificultad respiratoria, abdomen hundido, cianosis, sonidos respiratorios disminuidos.",
    "Gastrosquisis": "asas intestinales expuestas al nacer, riesgo de sepsis, dificultad para alimentarse.",
    "Onfalocele": "masa abdominal cubierta por membrana, dificultad respiratoria si es grande.",
    "Hidrocefalia": "fontanela abombada, macrocefalia, vómitos, irritabilidad, mirada en sol poniente.",
    "Anencefalia": "ausencia de bóveda craneana, exposición del tejido cerebral, letalidad inmediata.",
    "Espina bífida": "masa en región lumbar, parálisis de miembros inferiores, hidrocefalia, incontinencia.",
    "Síndrome de Down con complicaciones": "hipotonía, cardiopatías congénitas, retraso del desarrollo, infecciones frecuentes.",
    "Trastornos de la coagulación": "sangrado umbilical persistente, hematomas, hemorragias internas, petequias.",
    "Hemorragia pulmonar": "dificultad respiratoria, hemoptisis, cianosis, taquicardia, shock.",
    "Hipertensión pulmonar persistente": "cianosis, taquipnea, soplo cardíaco, dificultad respiratoria.",
    "Cardiomiopatía neonatal": "taquicardia, hepatomegalia, dificultad para alimentarse, cianosis.",
    "Taquicardia supraventricular": "palpitaciones, taquicardia >220 lpm, palidez, dificultad para alimentarse.",
    "Arritmias congénitas": "bradicardia o taquicardia, síncope, cianosis, letargo.",
    "Shock séptico": "hipotensión, taquicardia, piel moteada, letargo, oliguria.",
    "Trauma obstétrico": "hematomas, fracturas, parálisis braquial, convulsiones si hay hemorragia intracraneal.",
    "Lesión cerebral hipóxica": "convulsiones, hipotonía, apnea, reflejos ausentes, encefalopatía.",
    "Retraso en el inicio de la lactancia": "hipoglucemia, pérdida de peso, ictericia, deshidratación.",
    "Alimentación inadecuada": "hipoglucemia, deshidratación, pérdida de peso, letargo.",
    "Falta de atención neonatal inmediata": "hipotermia, hipoglucemia, dificultad respiratoria no tratada.",
    "Nacimiento en domicilio sin asistencia": "riesgo de asfixia, sepsis, hipotermia, hemorragia.",
    "Falta de acceso a cuidados intensivos neonatales": "evolución de patologías graves sin soporte vital.",
}

causas_sintomas_morta_infantil = {
    "Neumonía": "fiebre, tos, dificultad respiratoria, aleteo nasal, retracciones intercostales, cianosis.",
    "Diarrea aguda": "deposiciones líquidas frecuentes, deshidratación, ojos hundidos, boca seca, letargo.",
    "Malaria": "fiebre intermitente, escalofríos, sudoración, vómitos, palidez, convulsiones en casos graves.",
    "Sarampión": "fiebre alta, exantema maculopapular, tos, conjuntivitis, manchas de Koplik.",
    "VIH/SIDA": "pérdida de peso, infecciones recurrentes, fiebre persistente, candidiasis oral, retraso del crecimiento.",
    "Sepsis": "fiebre o hipotermia, letargo, rechazo al alimento, dificultad respiratoria, palidez, taquicardia.",
    "Meningitis": "fiebre alta, rigidez de nuca, vómitos, irritabilidad, fontanela abombada, convulsiones.",
    "Tuberculosis": "tos crónica, fiebre vespertina, pérdida de peso, sudoración nocturna, linfadenopatías.",
    "Desnutrición aguda severa": "emaciación, edema en piernas (kwashiorkor), apatía, piel seca, cabello quebradizo.",
    "Desnutrición crónica": "baja talla para la edad, retraso del desarrollo, debilidad, infecciones frecuentes.",
    "Asfixia por alimentos": "dificultad respiratoria súbita, cianosis, tos intensa, pérdida de conciencia.",
    "Ahogamiento": "pérdida de conciencia, cianosis, dificultad respiratoria, tos con espuma, paro cardiorrespiratorio.",
    "Quemaduras": "dolor intenso, ampollas, enrojecimiento o carbonización, fiebre si hay infección.",
    "Accidentes de tránsito": "politraumatismos, fracturas, pérdida de conciencia, hemorragias internas.",
    "Caídas graves": "hematomas, fracturas, vómitos, somnolencia, convulsiones si hay trauma craneal.",
    "Intoxicaciones accidentales": "vómitos, somnolencia, convulsiones, dificultad respiratoria, pupilas dilatadas o contraídas.",
    "Malformaciones congénitas": "signos variables según el órgano afectado (cianosis, dificultad para alimentarse, retraso del desarrollo).",
    "Cardiopatías congénitas": "cianosis, disnea, sudoración al alimentarse, soplo cardíaco, retraso ponderal.",
    "Cáncer infantil": "palidez, fiebre persistente, pérdida de peso, masas palpables, sangrados.",
    "Enfermedades respiratorias crónicas": "tos crónica, disnea, sibilancias, infecciones respiratorias recurrentes.",
    "Asma severa": "dificultad respiratoria, sibilancias, tos nocturna, uso de músculos accesorios.",
    "Bronquiolitis": "tos, fiebre, dificultad respiratoria, sibilancias, rechazo al alimento.",
    "Tos ferina": "accesos de tos intensos, vómitos post-tos, cianosis, estridor inspiratorio.",
    "Parálisis cerebral": "retraso motor, hipertonía o hipotonía, convulsiones, dificultad para tragar.",
    "Epilepsia no controlada": "crisis convulsivas recurrentes, pérdida de conciencia, confusión postictal.",
    "Enfermedades metabólicas hereditarias": "vómitos, letargo, hipoglucemia, convulsiones, retraso del desarrollo.",
    "Enfermedades genéticas raras": "dismorfismos faciales, retraso del desarrollo, convulsiones, alteraciones multisistémicas.",
    "Anemia falciforme": "palidez, ictericia, dolor óseo, infecciones frecuentes, crisis vasooclusivas.",
    "Talasemia": "palidez, fatiga, ictericia, hepatoesplenomegalia, deformidades óseas.",
    "Enfermedades autoinmunes": "fiebre persistente, erupciones cutáneas, artritis, fatiga, anemia.",
    "Hepatitis viral": "ictericia, fiebre, náuseas, vómitos, dolor abdominal.",
    "Dengue grave": "fiebre alta, sangrado, dolor abdominal, vómitos persistentes, shock.",
    "Zika congénito": "microcefalia, convulsiones, retraso del desarrollo, hipertonía.",
    "COVID-19": "fiebre, tos, disnea, diarrea, fatiga, pérdida del apetito.",
    "Infecciones urinarias complicadas": "fiebre, disuria, mal olor en la orina, irritabilidad.",
    "Otitis media supurada": "fiebre, dolor de oído, supuración, irritabilidad, pérdida auditiva.",
    "Abscesos cerebrales": "fiebre, vómitos, convulsiones, alteración del estado de conciencia.",
    "Tétanos": "rigidez muscular, trismo, espasmos, dificultad para tragar, fiebre.",
    "Rabia": "fiebre, hidrofobia, agitación, alucinaciones, parálisis, coma.",
    "Mordeduras de animales": "heridas abiertas, sangrado, dolor, riesgo de infección o rabia.",
    "Violencia doméstica": "hematomas, fracturas, retraimiento, miedo, cambios de comportamiento.",
    "Abuso infantil": "lesiones inexplicables, miedo a adultos, retraso en el desarrollo, retraimiento.",
    "Negligencia": "desnutrición, falta de higiene, infecciones frecuentes, retraso en el crecimiento.",
    "Falta de vacunación": "susceptibilidad a enfermedades prevenibles como sarampión, tétanos, tos ferina.",
    "Falta de acceso a atención médica": "evolución de enfermedades sin tratamiento, complicaciones evitables.",
    "Contaminación ambiental": "tos crónica, infecciones respiratorias, asma, irritación ocular.",
    "Agua no potable": "diarrea, vómitos, deshidratación, infecciones intestinales.",
    "Condiciones de pobreza extrema": "desnutrición, infecciones frecuentes, falta de higiene, falta de control médico.",
    "Trabajo infantil": "fatiga, lesiones, desnutrición, estrés, exposición a tóxicos.",
    "Desplazamiento por conflictos": "trauma psicológico, desnutrición, infecciones, falta de vacunación.",
}

causas_sintomas_morta_materna = {
    "Hemorragia posparto": "sangrado vaginal abundante, palidez, taquicardia, hipotensión, mareo, debilidad.",
    "Preeclampsia": "hipertensión, proteinuria, edema en cara y manos, cefalea, visión borrosa.",
    "Eclampsia": "convulsiones, pérdida de conciencia, hipertensión severa, dolor epigástrico.",
    "Infección puerperal": "fiebre >38°C, loquios fétidos, dolor abdominal, taquicardia.",
    "Sepsis": "fiebre alta, hipotensión, confusión, taquicardia, escalofríos.",
    "Ruptura uterina": "dolor abdominal súbito, sangrado vaginal, pérdida de tono uterino, sufrimiento fetal.",
    "Aborto inseguro": "sangrado vaginal, dolor pélvico, fiebre, secreción vaginal fétida.",
    "Embolia de líquido amniótico": "disnea súbita, hipotensión, cianosis, convulsiones, paro cardíaco.",
    "Complicaciones anestésicas": "dificultad respiratoria, hipotensión, bradicardia, pérdida de conciencia.",
    "Embarazo ectópico roto": "dolor abdominal agudo, sangrado vaginal, mareo, síncope.",
    "Trastornos hipertensivos del embarazo": "presión elevada, proteinuria, edema, visión borrosa.",
    "Placenta previa": "sangrado vaginal indoloro en el tercer trimestre, útero blando, sin dolor.",
    "Desprendimiento prematuro de placenta": "dolor abdominal intenso, sangrado vaginal, útero duro, sufrimiento fetal.",
    "Trombosis venosa profunda": "dolor en pierna, edema unilateral, enrojecimiento, calor local.",
    "Embolia pulmonar": "disnea súbita, dolor torácico, taquicardia, hemoptisis.",
    "Cardiopatía preexistente agravada": "disnea, fatiga, palpitaciones, edema periférico.",
    "Diabetes gestacional mal controlada": "poliuria, borrosa, infecciones frecuentes.",
    "Hepatitis viral": "ictericia, náuseas, vómitos, fatiga, dolor en hipocondrio derecho.",
    "VIH/SIDA": "fiebre recurrente, pérdida de peso, infecciones oportunistas, linfadenopatía.",
    "Malaria": "fiebre intermitente, escalofríos, sudoración, cefalea, anemia.",
    "Tuberculosis": "tos crónica, fiebre vespertina, sudoración nocturna, pérdida de peso.",
    "Anemia severa": "palidez, disnea, fatiga, taquicardia, mareo.",
    "Desnutrición": "pérdida de peso, debilidad, piel seca, caída de cabello, inmunosupresión.",
    "Cáncer ginecológico no diagnosticado": "sangrado anormal, dolor pélvico, pérdida de peso, fatiga.",
    "Lupus eritematoso sistémico": "artralgias, eritema malar, fiebre, proteinuria, fatiga.",
    "Enfermedad renal crónica": "edema, hipertensión, anemia, fatiga, náuseas.",
    "Trastornos tiroideos": "fatiga, intolerancia al frío/calor, cambios de peso, palpitaciones.",
    "Trastornos de coagulación": "sangrado prolongado, hematomas, petequias, sangrado espontáneo.",
    "Trauma obstétrico": "dolor pélvico, sangrado, hematomas, signos de shock.",
    "Cesárea complicada": "fiebre, dolor en herida, secreción purulenta, distensión abdominal.",
    "Retención placentaria": "sangrado persistente, útero aumentado, fiebre, dolor abdominal.",
    "Inversión uterina": "sangrado masivo, dolor intenso, útero ausente en palpación abdominal.",
    "Shock hipovolémico": "hipotensión, taquicardia, piel fría, confusión, oliguria.",
    "Hipertensión crónica": "cefalea, visión borrosa, epistaxis, edema.",
    "Infección urinaria complicada": "disuria, fiebre, dolor lumbar, náuseas.",
    "Endometritis": "fiebre, loquios fétidos, dolor uterino, malestar general.",
    "Hepatopatía aguda del embarazo": "ictericia, náuseas, dolor en hipocondrio derecho, coagulopatía.",
    "Síndrome HELLP": "hemólisis, enzimas hepáticas elevadas, plaquetas bajas, dolor epigástrico.",
    "Colestasis intrahepática": "prurito intenso, ictericia leve, elevación de bilirrubina.",
    "Hipoglucemia severa": "sudoración, temblores, confusión, pérdida de conciencia.",
    "Hipoxia materna": "disnea, cianosis, taquicardia, confusión.",
    "Complicaciones por COVID-19": "fiebre, tos, disnea, hipoxia, trombosis.",
    "Intoxicación por medicamentos": "náuseas, vómitos, alteración del sensorio, convulsiones.",
    "Complicaciones psiquiátricas": "tristeza profunda, ideación suicida, insomnio, ansiedad.",
    "Violencia doméstica": "hematomas, fracturas, ansiedad, retraimiento, miedo.",
    "Accidentes de tránsito durante el embarazo": "politraumatismo, dolor abdominal, sangrado, pérdida fetal.",
    "Falta de atención prenatal": "ausencia de control, detección tardía de complicaciones.",
    "Retraso en la atención obstétrica": "progresión de síntomas sin intervención, complicaciones evitables.",
    "Falta de acceso a servicios de emergencia": "evolución de cuadros críticos sin tratamiento.",
    "Errores médicos": "síntomas variables según el evento, desde infecciones hasta hemorragias no controladas.",
}

nombres_hombre = [
    "José", "Juan", "Carlos", "Luis", "Miguel", "Alejandro", "Daniel", "Manuel", 
    "Jesús", "Antonio", "Francisco", "David", "Ángel", "Pedro", "Jorge", "Andrés", 
    "Fernando", "Rafael", "Gabriel", "Diego", "Roberto", "Javier", "Mario", "Ricardo", 
    "Eduardo", "Alberto", "Victor", "Mauricio", "Héctor", "Raúl", "Oscar", "Pablo", 
    "Santiago", "Gustavo", "Felipe", "Ronaldo", "Samuel", "Guillermo", "Emilio", 
    "Hugo", "Iván", "Rubén", "Julio", "César", "Marco", "Esteban", "Enrique", 
    "Ramón", "Simón", "Tomás", "Nicolás", "Adrián", "Víctor", "Leonardo", "Óscar", 
    "Walter", "Rodrigo", "Salvador", "Ramiro", "Armando", "René", "Gerardo", 
    "Rigoberto", "Martín", "Saúl", "Alonso", "Isaac", "Erick", "Gregorio", "Ismael", 
    "Fidel", "Fausto", "Ulises", "Bernardo", "Teodoro", "Aarón", "Damián", "Jacobo", 
    "Noé", "Cristian", "Patricio", "Baltazar", "Mateo", "Elias", "Emanuel", 
    "Cristóbal", "Joaquín", "Gonzalo", "Julian", "Eugenio", "Lorenzo", "Ignacio", 
    "Fermín", "Lucas", "Maximiliano", "Agustín", "Valentín", "Benjamín", "Sebastián"
]

# Lista de 100 nombres de mujer comunes en Venezuela
nombres_mujer = [
    "María", "Ana", "Carmen", "Isabel", "Rosa", "Luisa", "Teresa", "Andrea", 
    "Carolina", "Patricia", "Laura", "Gabriela", "Camila", "Valentina", "Sofía", 
    "Daniela", "Mariana", "Victoria", "Fernanda", "Natalia", "Adriana", "Alejandra", 
    "Génesis", "Valeria", "Gabriela", "Antonieta", "Xiomara", "Yosmary", "Yulimar", 
    "Yusmary", "Mariángel", "Luisana", "Mayerling", "Lismar", "Oriana", "Ninoska", 
    "Lilian", "Yolanda", "Mercedes", "Diana", "Clara", "Elena", "Beatriz", "Rocío", 
    "Silvia", "Alicia", "Irma", "Margarita", "Gladys", "Marta", "Susana", "Julia", 
    "Esther", "Ruth", "Raquel", "Verónica", "Olivia", "Noelia", "Jimena", "Paula", 
    "Eva", "Inés", "Claudia", "Nora", "Elisa", "Miriam", "Lidia", "Cecilia", 
    "Rosa María", "Ángela", "Consuelo", "Dolores", "Catalina", "Bernarda", "Gloria", 
    "Milagros", "Esperanza", "Pilar", "Concepción", "Juana", "Petra", "Manuela", 
    "Francisca", "Josefina", "Lourdes", "Soledad", "Amparo", "Lucía", "Rita", 
    "Edith", "Matilde", "Emma", "Alba", "Berta", "Elvira", "Irene", "Olga", 
    "Nelly", "Wilmer", "Yajaira", "Yusbely", "Zulay", "Zulimar"
]

# Lista de 200 apellidos comunes en Venezuela
apellidos = [
    "González", "Rodríguez", "Pérez", "García", "Martínez", "López", "Hernández", 
    "Gómez", "Díaz", "Vásquez", "Rojas", "Morales", "Castillo", "Ramírez", "Ramos", 
    "Suárez", "Romero", "Torres", "Flores", "Rivera", "Álvarez", "Mendoza", "Vargas", 
    "Medina", "Guerrero", "Reyes", "Castro", "Ortiz", "Silva", "Núñez", "Jiménez", 
    "Molina", "Delgado", "Peña", "Cruz", "Acosta", "Herrera", "Fernández", "Vega", 
    "Chávez", "Cabrera", "Briceño", "Barrios", "Aguilar", "Paredes", "Salazar", 
    "Mejía", "Quintana", "Contreras", "Arias", "Parra", "Sandoval", "Bravo", "Miranda", 
    "Zambrano", "Montes", "Escobar", "Cárdenas", "Campos", "León", "Fuentes", "Márquez", 
    "Valera", "Figueroa", "Rivas", "Padilla", "Calderón", "Bermúdez", "Sánchez", 
    "Méndez", "Rangel", "Duarte", "Brito", "Cordero", "Moreno", "Pinto", "Urdaneta", 
    "Marín", "Villalobos", "Peraza", "Quintero", "Velásquez", "Navarro", "Rincón", 
    "Marcano", "Barreto", "Salas", "Lara", "Zambrano", "Arroyo", "Carrillo", "Carvajal", 
    "Guerra", "Ibarra", "Serrano", "Valdez", "Galindo", "Véliz", "Yánez", "Zapata", 
    "Arévalo", "Bautista", "Bernal", "Blanco", "Bustamante", "Cano", "Cantillo", 
    "Caraballo", "Cedeno", "Colina", "Correa", "Cortez", "Del Castillo", "Estrada", 
    "Fajardo", "Gallegos", "Gil", "Granados", "Guevara", "Gutiérrez", "Henríquez", 
    "Izquierdo", "Jaimes", "Lozano", "Lucena", "Maldonado", "Marques", "Mora", 
    "Murillo", "Naranjo", "Navia", "Olivo", "Ortega", "Ospina", "Palma", "Palacios", 
    "Paz", "Pereira", "Prieto", "Pulido", "Quiñones", "Quiroz", "Redondo", "Restrepo", 
    "Roldán", "Rosales", "Ruiz", "Salcedo", "Salinas", "Santana", "Sierra", "Soto", 
    "Téllez", "Toro", "Trejo", "Trujillo", "Uribe", "Valencia", "Valenzuela", 
    "Varela", "Vera", "Vidal", "Villegas", "Yépez", "Zabala", "Zambrano", "Zambrano", 
    "Abreu", "Alvarado", "Amaya", "Aranda", "Arcila", "Arguello", "Arismendi", 
    "Arjona", "Arrate", "Arteaga", "Asuaje", "Aular", "Avila", "Azocar", "Báez", 
    "Bandres", "Barboza", "Baron", "Barros", "Bello", "Benitez", "Betancourt", 
    "Bohorquez", "Bolivar", "Borjas", "Briceño", "Burgos", "Caballero", "Cadenas", 
    "Calles", "Campo", "Cardona", "Carreño", "Carvajal", "Casas", "Castañeda", 
    "Causado", "Celis", "Cerrada", "Cicero", "Cisneros", "Colmenares", "Consalvi"
]
